'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

Namespace MSNWebServices
    '
    'This source code was auto-generated by wsdl, Version=2.0.50727.42.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="ReportingSoap", [Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class Reporting
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private apiUserAuthHeaderValueField As ApiUserAuthHeader

        Private RequestBIReportOperationCompleted As System.Threading.SendOrPostCallback

        Private GetAPIReportStatusOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = "https://adcenterapi.microsoft.com/v4/Reporting/Reporting.asmx"
        End Sub

        Public Property ApiUserAuthHeaderValue() As ApiUserAuthHeader
            Get
                Return Me.apiUserAuthHeaderValueField
            End Get
            Set(ByVal value As ApiUserAuthHeader)
                Me.apiUserAuthHeaderValueField = Value
            End Set
        End Property

        '''<remarks/>
        Public Event RequestBIReportCompleted As RequestBIReportCompletedEventHandler

        '''<remarks/>
        Public Event GetAPIReportStatusCompleted As GetAPIReportStatusCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ApiUserAuthHeaderValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://adcenter.microsoft.com/syncapis/RequestBIReport", RequestNamespace:="http://adcenter.microsoft.com/syncapis", ResponseNamespace:="http://adcenter.microsoft.com/syncapis", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function RequestBIReport(ByVal APIFlags As Integer, ByVal request As ReportRequest) As String
            Dim results() As Object = Me.Invoke("RequestBIReport", New Object() {APIFlags, request})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Function BeginRequestBIReport(ByVal APIFlags As Integer, ByVal request As ReportRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RequestBIReport", New Object() {APIFlags, request}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndRequestBIReport(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub RequestBIReportAsync(ByVal APIFlags As Integer, ByVal request As ReportRequest)
            Me.RequestBIReportAsync(APIFlags, request, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub RequestBIReportAsync(ByVal APIFlags As Integer, ByVal request As ReportRequest, ByVal userState As Object)
            If (Me.RequestBIReportOperationCompleted Is Nothing) Then
                Me.RequestBIReportOperationCompleted = AddressOf Me.OnRequestBIReportOperationCompleted
            End If
            Me.InvokeAsync("RequestBIReport", New Object() {APIFlags, request}, Me.RequestBIReportOperationCompleted, userState)
        End Sub

        Private Sub OnRequestBIReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.RequestBIReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RequestBIReportCompleted(Me, New RequestBIReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ApiUserAuthHeaderValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://adcenter.microsoft.com/syncapis/GetAPIReportStatus", RequestNamespace:="http://adcenter.microsoft.com/syncapis", ResponseNamespace:="http://adcenter.microsoft.com/syncapis", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function GetAPIReportStatus(ByVal APIFlags As Integer, ByVal APIRequestId As String) As APIReportStatusType
            Dim results() As Object = Me.Invoke("GetAPIReportStatus", New Object() {APIFlags, APIRequestId})
            Return CType(results(0), APIReportStatusType)
        End Function

        '''<remarks/>
        Public Function BeginGetAPIReportStatus(ByVal APIFlags As Integer, ByVal APIRequestId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAPIReportStatus", New Object() {APIFlags, APIRequestId}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndGetAPIReportStatus(ByVal asyncResult As System.IAsyncResult) As APIReportStatusType
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), APIReportStatusType)
        End Function

        '''<remarks/>
        Public Overloads Sub GetAPIReportStatusAsync(ByVal APIFlags As Integer, ByVal APIRequestId As String)
            Me.GetAPIReportStatusAsync(APIFlags, APIRequestId, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub GetAPIReportStatusAsync(ByVal APIFlags As Integer, ByVal APIRequestId As String, ByVal userState As Object)
            If (Me.GetAPIReportStatusOperationCompleted Is Nothing) Then
                Me.GetAPIReportStatusOperationCompleted = AddressOf Me.OnGetAPIReportStatusOperationCompleted
            End If
            Me.InvokeAsync("GetAPIReportStatus", New Object() {APIFlags, APIRequestId}, Me.GetAPIReportStatusOperationCompleted, userState)
        End Sub

        Private Sub OnGetAPIReportStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAPIReportStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAPIReportStatusCompleted(Me, New GetAPIReportStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis", IsNullable:=False)> _
    Partial Public Class ApiUserAuthHeader
        Inherits System.Web.Services.Protocols.SoapHeader

        Private userNameField As String

        Private passwordField As String

        Private userAccessKeyField As String

        Private anyAttrField() As System.Xml.XmlAttribute

        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set(ByVal value As String)
                Me.userNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set(ByVal value As String)
                Me.passwordField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property UserAccessKey() As String
            Get
                Return Me.userAccessKeyField
            End Get
            Set(ByVal value As String)
                Me.userAccessKeyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()> _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set(ByVal value As System.Xml.XmlAttribute())
                Me.anyAttrField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class APIReportStatusType

        Private reportStatusField As APIStatusType

        Private reportDownloadURLField As String

        '''<remarks/>
        Public Property ReportStatus() As APIStatusType
            Get
                Return Me.reportStatusField
            End Get
            Set(ByVal value As APIStatusType)
                Me.reportStatusField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ReportDownloadURL() As String
            Get
                Return Me.reportDownloadURLField
            End Get
            Set(ByVal value As String)
                Me.reportDownloadURLField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum APIStatusType

        '''<remarks/>
        REQUEST_PENDING

        '''<remarks/>
        REQUEST_IN_PROGRESS

        '''<remarks/>
        SUCCESS_PARTIAL

        '''<remarks/>
        SUCCESS

        '''<remarks/>
        FAILED_APPLICATION_ERROR

        '''<remarks/>
        FAILED_RESULT_EXPIRED

        '''<remarks/>
        FAILED_USER_NOT_AUTHORIZED

        '''<remarks/>
        FAILED_SYSTEM_UNDERGOING_MAINTENANCE

        '''<remarks/>
        FAILED_DUPLICATE_KEYWORD

        '''<remarks/>
        FAILED_NOT_KEYWORD_MISSING_AMT

        '''<remarks/>
        FAILED_NOT_KEYWORD_MATCHES_KEYWORD

        '''<remarks/>
        FAILED_REPORT_GENERATION

        '''<remarks/>
        FAILED_UNAUTHORIZED_ACCESS

        '''<remarks/>
        FAILED_INVALID_ARGUMENT

        '''<remarks/>
        FAILED_NOT_YET_IMPLEMENTED

        '''<remarks/>
        FAILED_REQUEST_INPUT_FILE_TOO_BIG

        '''<remarks/>
        FAILED_BATCH_ERROR

        '''<remarks/>
        FAILED_MALFORMED_XML_INPUT_FILE

        '''<remarks/>
        FAILED_STARTDATE_INVALID_OR_MISSING

        '''<remarks/>
        FAILED_DATERANGE_INVALID

        '''<remarks/>
        FAILED_DISTRIBUTIONSITE_NOT_SUPPORTED

        '''<remarks/>
        FAILED_BID_AMOUNT_BELOW_FLOOR_PRICE

        '''<remarks/>
        FAILED_ACCOUNTID_INVALID_OR_MISSING

        '''<remarks/>
        FAILED_CAMPAIGNID_INVALID_OR_MISSING

        '''<remarks/>
        FAILED_ORDERID_INVALID_OR_MISSING

        '''<remarks/>
        FAILED_QUOTA_EXCEEDED

        '''<remarks/>
        FAILED_DUE_TO_SYSTEM_ERROR

        '''<remarks/>
        FAILED_MISSING_ADS_INFORMATION

        '''<remarks/>
        FAILED_UNDEFINED_APPLICATION_ERROR
    End Enum

    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(KeywordPerformanceReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AdParameterReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(MetroAreaDemographicReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BudgetSummaryReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AccountPerformanceReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(OrderPerformanceReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CampaignPerformanceReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AdPerformanceReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AgeGenderDemographicReportRequest)), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public MustInherit Class ReportRequest

        Private startDateField As System.Nullable(Of Date)

        Private endDateField As System.Nullable(Of Date)

        Private reportDatesField() As Date

        Private reportLanguageField As ReportLanguageType

        Private formatField As APIResultFileType

        Private allNoneField As System.Nullable(Of Boolean)

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property StartDate() As System.Nullable(Of Date)
            Get
                Return Me.startDateField
            End Get
            Set(ByVal value As System.Nullable(Of Date))
                Me.startDateField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property EndDate() As System.Nullable(Of Date)
            Get
                Return Me.endDateField
            End Get
            Set(ByVal value As System.Nullable(Of Date))
                Me.endDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ReportDates() As Date()
            Get
                Return Me.reportDatesField
            End Get
            Set(ByVal value As Date())
                Me.reportDatesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ReportLanguage() As ReportLanguageType
            Get
                Return Me.reportLanguageField
            End Get
            Set(ByVal value As ReportLanguageType)
                Me.reportLanguageField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Format() As APIResultFileType
            Get
                Return Me.formatField
            End Get
            Set(ByVal value As APIResultFileType)
                Me.formatField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property AllNone() As System.Nullable(Of Boolean)
            Get
                Return Me.allNoneField
            End Get
            Set(ByVal value As System.Nullable(Of Boolean))
                Me.allNoneField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum ReportLanguageType

        '''<remarks/>
        English

        '''<remarks/>
        French
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum APIResultFileType

        '''<remarks/>
        CSV

        '''<remarks/>
        TSV

        '''<remarks/>
        XML
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class KeywordPerformanceReportRequest
        Inherits ReportRequest

        Private reportDateRangeField As ReportDateRangeType

        Private reportAggregationField As System.Nullable(Of ReportAggregationType)

        Private accountIdField As Integer

        Private campaignIdsField() As Integer

        Private optionalMeasuresField() As KeywordPerformanceReportOptionalMeasure

        Private optionalColumnsField() As KeywordPerformanceReportOptionalColumn

        '''<remarks/>
        Public Property ReportDateRange() As ReportDateRangeType
            Get
                Return Me.reportDateRangeField
            End Get
            Set(ByVal value As ReportDateRangeType)
                Me.reportDateRangeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property ReportAggregation() As System.Nullable(Of ReportAggregationType)
            Get
                Return Me.reportAggregationField
            End Get
            Set(ByVal value As System.Nullable(Of ReportAggregationType))
                Me.reportAggregationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AccountId() As Integer
            Get
                Return Me.accountIdField
            End Get
            Set(ByVal value As Integer)
                Me.accountIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CampaignIds() As Integer()
            Get
                Return Me.campaignIdsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignIdsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalMeasures() As KeywordPerformanceReportOptionalMeasure()
            Get
                Return Me.optionalMeasuresField
            End Get
            Set(ByVal value As KeywordPerformanceReportOptionalMeasure())
                Me.optionalMeasuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalColumns() As KeywordPerformanceReportOptionalColumn()
            Get
                Return Me.optionalColumnsField
            End Get
            Set(ByVal value As KeywordPerformanceReportOptionalColumn())
                Me.optionalColumnsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum ReportDateRangeType

        '''<remarks/>
        TodaySummary

        '''<remarks/>
        YesterdaySummary

        '''<remarks/>
        LastSevenDaysSummary

        '''<remarks/>
        ThisMonthSummary

        '''<remarks/>
        LastMonthSummary

        '''<remarks/>
        Today

        '''<remarks/>
        Yesterday

        '''<remarks/>
        LastSevenDays

        '''<remarks/>
        ThisMonthInDays

        '''<remarks/>
        LastMonthInDays

        '''<remarks/>
        TodayInHours

        '''<remarks/>
        YesterdayInHours

        '''<remarks/>
        ThisWeek

        '''<remarks/>
        LastWeek

        '''<remarks/>
        Last4Weeks

        '''<remarks/>
        ThisMonth

        '''<remarks/>
        LastMonth

        '''<remarks/>
        Last3Months

        '''<remarks/>
        Last6Months

        '''<remarks/>
        LastYearInMonths

        '''<remarks/>
        ThisYear

        '''<remarks/>
        LastYear

        '''<remarks/>
        Customized

        '''<remarks/>
        CustomizedDataRange
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum ReportAggregationType

        '''<remarks/>
        Hour

        '''<remarks/>
        Day

        '''<remarks/>
        Week

        '''<remarks/>
        Month

        '''<remarks/>
        Year
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum KeywordPerformanceReportOptionalMeasure

        '''<remarks/>
        None

        '''<remarks/>
        Conversions

        '''<remarks/>
        ConversionRate

        '''<remarks/>
        CostPerConversion
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum KeywordPerformanceReportOptionalColumn

        '''<remarks/>
        None

        '''<remarks/>
        AccountNumber

        '''<remarks/>
        DistributionChannelName

        '''<remarks/>
        KeywordOrderName

        '''<remarks/>
        DestinationURL

        '''<remarks/>
        ProductName

        '''<remarks/>
        MaxCPC

        '''<remarks/>
        CurrencyCode

        '''<remarks/>
        MatchTypeDescription

        '''<remarks/>
        MediumName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class AdParameterReportRequest
        Inherits ReportRequest

        Private reportDateRangeField As ReportDateRangeNoHourlyType

        Private reportAggregationField As System.Nullable(Of ReportAggregationNoHourlyType)

        Private accountIdField As Integer

        Private campaignIdsField() As Integer

        Private optionalMeasuresField() As AdParameterReportOptionalMeasure

        Private optionalColumnsField() As AdParameterReportOptionalColumn

        '''<remarks/>
        Public Property ReportDateRange() As ReportDateRangeNoHourlyType
            Get
                Return Me.reportDateRangeField
            End Get
            Set(ByVal value As ReportDateRangeNoHourlyType)
                Me.reportDateRangeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property ReportAggregation() As System.Nullable(Of ReportAggregationNoHourlyType)
            Get
                Return Me.reportAggregationField
            End Get
            Set(ByVal value As System.Nullable(Of ReportAggregationNoHourlyType))
                Me.reportAggregationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AccountId() As Integer
            Get
                Return Me.accountIdField
            End Get
            Set(ByVal value As Integer)
                Me.accountIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CampaignIds() As Integer()
            Get
                Return Me.campaignIdsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignIdsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalMeasures() As AdParameterReportOptionalMeasure()
            Get
                Return Me.optionalMeasuresField
            End Get
            Set(ByVal value As AdParameterReportOptionalMeasure())
                Me.optionalMeasuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalColumns() As AdParameterReportOptionalColumn()
            Get
                Return Me.optionalColumnsField
            End Get
            Set(ByVal value As AdParameterReportOptionalColumn())
                Me.optionalColumnsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum ReportDateRangeNoHourlyType

        '''<remarks/>
        TodaySummary

        '''<remarks/>
        YesterdaySummary

        '''<remarks/>
        LastSevenDaysSummary

        '''<remarks/>
        ThisMonthSummary

        '''<remarks/>
        LastMonthSummary

        '''<remarks/>
        Today

        '''<remarks/>
        Yesterday

        '''<remarks/>
        LastSevenDays

        '''<remarks/>
        ThisMonthInDays

        '''<remarks/>
        LastMonthInDays

        '''<remarks/>
        ThisWeek

        '''<remarks/>
        LastWeek

        '''<remarks/>
        Last4Weeks

        '''<remarks/>
        ThisMonth

        '''<remarks/>
        LastMonth

        '''<remarks/>
        Last3Months

        '''<remarks/>
        Last6Months

        '''<remarks/>
        LastYearInMonths

        '''<remarks/>
        ThisYear

        '''<remarks/>
        LastYear

        '''<remarks/>
        Customized

        '''<remarks/>
        CustomizedDataRange
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum ReportAggregationNoHourlyType

        '''<remarks/>
        Day

        '''<remarks/>
        Week

        '''<remarks/>
        Month

        '''<remarks/>
        Year
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum AdParameterReportOptionalMeasure

        '''<remarks/>
        None

        '''<remarks/>
        Conversions

        '''<remarks/>
        ConversionRate

        '''<remarks/>
        CostPerConversion
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum AdParameterReportOptionalColumn

        '''<remarks/>
        None

        '''<remarks/>
        AccountNumber

        '''<remarks/>
        DistributionChannelName

        '''<remarks/>
        Keyword

        '''<remarks/>
        ProductName

        '''<remarks/>
        CurrencyCode

        '''<remarks/>
        MediumName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class MetroAreaDemographicReportRequest
        Inherits ReportRequest

        Private reportDateRangeField As ReportDateRangeNoHourlyType

        Private reportAggregationField As System.Nullable(Of ReportAggregationNoHourlyType)

        Private accountIdField As Integer

        Private campaignIdsField() As Integer

        Private optionalMeasuresField() As MetroAreaDemographicReportOptionalMeasure

        Private optionalColumnsField() As MetroAreaDemographicReportOptionalColumn

        '''<remarks/>
        Public Property ReportDateRange() As ReportDateRangeNoHourlyType
            Get
                Return Me.reportDateRangeField
            End Get
            Set(ByVal value As ReportDateRangeNoHourlyType)
                Me.reportDateRangeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property ReportAggregation() As System.Nullable(Of ReportAggregationNoHourlyType)
            Get
                Return Me.reportAggregationField
            End Get
            Set(ByVal value As System.Nullable(Of ReportAggregationNoHourlyType))
                Me.reportAggregationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AccountId() As Integer
            Get
                Return Me.accountIdField
            End Get
            Set(ByVal value As Integer)
                Me.accountIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CampaignIds() As Integer()
            Get
                Return Me.campaignIdsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignIdsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalMeasures() As MetroAreaDemographicReportOptionalMeasure()
            Get
                Return Me.optionalMeasuresField
            End Get
            Set(ByVal value As MetroAreaDemographicReportOptionalMeasure())
                Me.optionalMeasuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalColumns() As MetroAreaDemographicReportOptionalColumn()
            Get
                Return Me.optionalColumnsField
            End Get
            Set(ByVal value As MetroAreaDemographicReportOptionalColumn())
                Me.optionalColumnsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum MetroAreaDemographicReportOptionalMeasure

        '''<remarks/>
        None
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum MetroAreaDemographicReportOptionalColumn

        '''<remarks/>
        None

        '''<remarks/>
        AccountNumber

        '''<remarks/>
        CampaignName

        '''<remarks/>
        DistributionChannelName

        '''<remarks/>
        ProductName

        '''<remarks/>
        CountryName

        '''<remarks/>
        MetroAreaName

        '''<remarks/>
        CurrencyCode

        '''<remarks/>
        HourBucket

        '''<remarks/>
        SubGeographyName

        '''<remarks/>
        MediumName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class BudgetSummaryReportRequest
        Inherits ReportRequest

        Private reportDateRangeField As BudgetSummaryReportDateRangeType

        Private reportAggregationField As System.Nullable(Of BudgetSummaryReportAggregationType)

        Private accountIdsField() As Integer

        Private optionalMeasuresField() As BudgetSummaryReportOptionalMeasure

        Private optionalColumnsField() As BudgetSummaryReportOptionalColumn

        '''<remarks/>
        Public Property ReportDateRange() As BudgetSummaryReportDateRangeType
            Get
                Return Me.reportDateRangeField
            End Get
            Set(ByVal value As BudgetSummaryReportDateRangeType)
                Me.reportDateRangeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property ReportAggregation() As System.Nullable(Of BudgetSummaryReportAggregationType)
            Get
                Return Me.reportAggregationField
            End Get
            Set(ByVal value As System.Nullable(Of BudgetSummaryReportAggregationType))
                Me.reportAggregationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AccountIds() As Integer()
            Get
                Return Me.accountIdsField
            End Get
            Set(ByVal value As Integer())
                Me.accountIdsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalMeasures() As BudgetSummaryReportOptionalMeasure()
            Get
                Return Me.optionalMeasuresField
            End Get
            Set(ByVal value As BudgetSummaryReportOptionalMeasure())
                Me.optionalMeasuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalColumns() As BudgetSummaryReportOptionalColumn()
            Get
                Return Me.optionalColumnsField
            End Get
            Set(ByVal value As BudgetSummaryReportOptionalColumn())
                Me.optionalColumnsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum BudgetSummaryReportDateRangeType

        '''<remarks/>
        Today

        '''<remarks/>
        Yesterday

        '''<remarks/>
        LastSevenDays

        '''<remarks/>
        ThisMonthInDays

        '''<remarks/>
        LastMonthInDays

        '''<remarks/>
        Customized

        '''<remarks/>
        CustomizedDataRange
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum BudgetSummaryReportAggregationType

        '''<remarks/>
        Day
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum BudgetSummaryReportOptionalMeasure

        '''<remarks/>
        None

        '''<remarks/>
        ParticipationRate
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum BudgetSummaryReportOptionalColumn

        '''<remarks/>
        None
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class AccountPerformanceReportRequest
        Inherits ReportRequest

        Private reportDateRangeField As ReportDateRangeType

        Private reportAggregationField As System.Nullable(Of ReportAggregationType)

        Private accountIdField As Integer

        Private optionalMeasuresField() As AccountPerformanceReportOptionalMeasure

        Private optionalColumnsField() As AccountPerformanceReportOptionalColumn

        '''<remarks/>
        Public Property ReportDateRange() As ReportDateRangeType
            Get
                Return Me.reportDateRangeField
            End Get
            Set(ByVal value As ReportDateRangeType)
                Me.reportDateRangeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property ReportAggregation() As System.Nullable(Of ReportAggregationType)
            Get
                Return Me.reportAggregationField
            End Get
            Set(ByVal value As System.Nullable(Of ReportAggregationType))
                Me.reportAggregationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AccountId() As Integer
            Get
                Return Me.accountIdField
            End Get
            Set(ByVal value As Integer)
                Me.accountIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalMeasures() As AccountPerformanceReportOptionalMeasure()
            Get
                Return Me.optionalMeasuresField
            End Get
            Set(ByVal value As AccountPerformanceReportOptionalMeasure())
                Me.optionalMeasuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalColumns() As AccountPerformanceReportOptionalColumn()
            Get
                Return Me.optionalColumnsField
            End Get
            Set(ByVal value As AccountPerformanceReportOptionalColumn())
                Me.optionalColumnsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum AccountPerformanceReportOptionalMeasure

        '''<remarks/>
        None

        '''<remarks/>
        Conversions

        '''<remarks/>
        ConversionRate

        '''<remarks/>
        CostPerConversion

        '''<remarks/>
        LowQualityClicks

        '''<remarks/>
        LowQualityClicksPercent

        '''<remarks/>
        LowQualityImpressions

        '''<remarks/>
        LowQualityImpressionsPercent

        '''<remarks/>
        LowQualityConversions

        '''<remarks/>
        LowQualityConversionRate
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum AccountPerformanceReportOptionalColumn

        '''<remarks/>
        None

        '''<remarks/>
        AccountNumber

        '''<remarks/>
        ProductName

        '''<remarks/>
        CurrencyCode

        '''<remarks/>
        MediumName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class OrderPerformanceReportRequest
        Inherits ReportRequest

        Private reportDateRangeField As ReportDateRangeType

        Private reportAggregationField As System.Nullable(Of ReportAggregationType)

        Private accountIdField As Integer

        Private campaignIdsField() As Integer

        Private optionalMeasuresField() As OrderPerformanceReportOptionalMeasure

        Private optionalColumnsField() As OrderPerformanceReportOptionalColumn

        '''<remarks/>
        Public Property ReportDateRange() As ReportDateRangeType
            Get
                Return Me.reportDateRangeField
            End Get
            Set(ByVal value As ReportDateRangeType)
                Me.reportDateRangeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property ReportAggregation() As System.Nullable(Of ReportAggregationType)
            Get
                Return Me.reportAggregationField
            End Get
            Set(ByVal value As System.Nullable(Of ReportAggregationType))
                Me.reportAggregationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AccountId() As Integer
            Get
                Return Me.accountIdField
            End Get
            Set(ByVal value As Integer)
                Me.accountIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CampaignIds() As Integer()
            Get
                Return Me.campaignIdsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignIdsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalMeasures() As OrderPerformanceReportOptionalMeasure()
            Get
                Return Me.optionalMeasuresField
            End Get
            Set(ByVal value As OrderPerformanceReportOptionalMeasure())
                Me.optionalMeasuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalColumns() As OrderPerformanceReportOptionalColumn()
            Get
                Return Me.optionalColumnsField
            End Get
            Set(ByVal value As OrderPerformanceReportOptionalColumn())
                Me.optionalColumnsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum OrderPerformanceReportOptionalMeasure

        '''<remarks/>
        None

        '''<remarks/>
        Conversions

        '''<remarks/>
        ConversionRate

        '''<remarks/>
        CostPerConversion
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum OrderPerformanceReportOptionalColumn

        '''<remarks/>
        None

        '''<remarks/>
        AccountNumber

        '''<remarks/>
        DistributionChannelName

        '''<remarks/>
        ProductName

        '''<remarks/>
        StatusName

        '''<remarks/>
        CurrencyCode

        '''<remarks/>
        MediumName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class CampaignPerformanceReportRequest
        Inherits ReportRequest

        Private reportDateRangeField As ReportDateRangeType

        Private reportAggregationField As System.Nullable(Of ReportAggregationType)

        Private accountIdField As Integer

        Private campaignIdsField() As Integer

        Private optionalMeasuresField() As CampaignPerformanceReportOptionalMeasure

        Private optionalColumnsField() As CampaignPerformanceReportOptionalColumn

        '''<remarks/>
        Public Property ReportDateRange() As ReportDateRangeType
            Get
                Return Me.reportDateRangeField
            End Get
            Set(ByVal value As ReportDateRangeType)
                Me.reportDateRangeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property ReportAggregation() As System.Nullable(Of ReportAggregationType)
            Get
                Return Me.reportAggregationField
            End Get
            Set(ByVal value As System.Nullable(Of ReportAggregationType))
                Me.reportAggregationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AccountId() As Integer
            Get
                Return Me.accountIdField
            End Get
            Set(ByVal value As Integer)
                Me.accountIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CampaignIds() As Integer()
            Get
                Return Me.campaignIdsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignIdsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalMeasures() As CampaignPerformanceReportOptionalMeasure()
            Get
                Return Me.optionalMeasuresField
            End Get
            Set(ByVal value As CampaignPerformanceReportOptionalMeasure())
                Me.optionalMeasuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalColumns() As CampaignPerformanceReportOptionalColumn()
            Get
                Return Me.optionalColumnsField
            End Get
            Set(ByVal value As CampaignPerformanceReportOptionalColumn())
                Me.optionalColumnsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum CampaignPerformanceReportOptionalMeasure

        '''<remarks/>
        None

        '''<remarks/>
        Conversions

        '''<remarks/>
        ConversionRate

        '''<remarks/>
        CostPerConversion

        '''<remarks/>
        LowQualityClicks

        '''<remarks/>
        LowQualityClicksPercent

        '''<remarks/>
        LowQualityImpressions

        '''<remarks/>
        LowQualityImpressionsPercent

        '''<remarks/>
        LowQualityConversions

        '''<remarks/>
        LowQualityConversionRate
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum CampaignPerformanceReportOptionalColumn

        '''<remarks/>
        None

        '''<remarks/>
        AccountNumber

        '''<remarks/>
        ProductName

        '''<remarks/>
        StatusName

        '''<remarks/>
        CurrencyCode

        '''<remarks/>
        MediumName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class AdPerformanceReportRequest
        Inherits ReportRequest

        Private reportDateRangeField As ReportDateRangeNoHourlyType

        Private reportAggregationField As System.Nullable(Of ReportAggregationNoHourlyType)

        Private accountIdField As Integer

        Private campaignIdsField() As Integer

        Private optionalMeasuresField() As AdPerformanceReportOptionalMeasure

        Private optionalColumnsField() As AdPerformanceReportOptionalColumn

        '''<remarks/>
        Public Property ReportDateRange() As ReportDateRangeNoHourlyType
            Get
                Return Me.reportDateRangeField
            End Get
            Set(ByVal value As ReportDateRangeNoHourlyType)
                Me.reportDateRangeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property ReportAggregation() As System.Nullable(Of ReportAggregationNoHourlyType)
            Get
                Return Me.reportAggregationField
            End Get
            Set(ByVal value As System.Nullable(Of ReportAggregationNoHourlyType))
                Me.reportAggregationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AccountId() As Integer
            Get
                Return Me.accountIdField
            End Get
            Set(ByVal value As Integer)
                Me.accountIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CampaignIds() As Integer()
            Get
                Return Me.campaignIdsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignIdsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalMeasures() As AdPerformanceReportOptionalMeasure()
            Get
                Return Me.optionalMeasuresField
            End Get
            Set(ByVal value As AdPerformanceReportOptionalMeasure())
                Me.optionalMeasuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalColumns() As AdPerformanceReportOptionalColumn()
            Get
                Return Me.optionalColumnsField
            End Get
            Set(ByVal value As AdPerformanceReportOptionalColumn())
                Me.optionalColumnsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum AdPerformanceReportOptionalMeasure

        '''<remarks/>
        None

        '''<remarks/>
        Conversions

        '''<remarks/>
        ConversionRate

        '''<remarks/>
        CostPerConversion
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum AdPerformanceReportOptionalColumn

        '''<remarks/>
        None

        '''<remarks/>
        AccountNumber

        '''<remarks/>
        AdDescription

        '''<remarks/>
        DistributionChannelName

        '''<remarks/>
        KeywordOrderName

        '''<remarks/>
        ProductName

        '''<remarks/>
        CurrencyCode

        '''<remarks/>
        AdTitle

        '''<remarks/>
        MediumName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Partial Public Class AgeGenderDemographicReportRequest
        Inherits ReportRequest

        Private reportDateRangeField As ReportDateRangeNoHourlyType

        Private reportAggregationField As System.Nullable(Of ReportAggregationNoHourlyType)

        Private accountIdField As Integer

        Private campaignIdsField() As Integer

        Private optionalMeasuresField() As AgeGenderDemographicReportOptionalMeasure

        Private optionalColumnsField() As AgeGenderDemographicReportOptionalColumn

        '''<remarks/>
        Public Property ReportDateRange() As ReportDateRangeNoHourlyType
            Get
                Return Me.reportDateRangeField
            End Get
            Set(ByVal value As ReportDateRangeNoHourlyType)
                Me.reportDateRangeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
        Public Property ReportAggregation() As System.Nullable(Of ReportAggregationNoHourlyType)
            Get
                Return Me.reportAggregationField
            End Get
            Set(ByVal value As System.Nullable(Of ReportAggregationNoHourlyType))
                Me.reportAggregationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AccountId() As Integer
            Get
                Return Me.accountIdField
            End Get
            Set(ByVal value As Integer)
                Me.accountIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CampaignIds() As Integer()
            Get
                Return Me.campaignIdsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignIdsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalMeasures() As AgeGenderDemographicReportOptionalMeasure()
            Get
                Return Me.optionalMeasuresField
            End Get
            Set(ByVal value As AgeGenderDemographicReportOptionalMeasure())
                Me.optionalMeasuresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptionalColumns() As AgeGenderDemographicReportOptionalColumn()
            Get
                Return Me.optionalColumnsField
            End Get
            Set(ByVal value As AgeGenderDemographicReportOptionalColumn())
                Me.optionalColumnsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum AgeGenderDemographicReportOptionalMeasure

        '''<remarks/>
        None
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://adcenter.microsoft.com/syncapis")> _
    Public Enum AgeGenderDemographicReportOptionalColumn

        '''<remarks/>
        None

        '''<remarks/>
        AccountNumber

        '''<remarks/>
        CampaignName

        '''<remarks/>
        DistributionChannelName

        '''<remarks/>
        ProductName

        '''<remarks/>
        MediumName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub RequestBIReportCompletedEventHandler(ByVal sender As Object, ByVal e As RequestBIReportCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class RequestBIReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub GetAPIReportStatusCompletedEventHandler(ByVal sender As Object, ByVal e As GetAPIReportStatusCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class GetAPIReportStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As APIReportStatusType
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), APIReportStatusType)
            End Get
        End Property
    End Class
End Namespace