'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3625
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'
Namespace GoogleWebServices
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ReportDefinitionServiceSoapBinding", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201209")>  _
    Partial Public Class ReportDefinitionService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private requestHeaderField As RequestHeader
        
        Private responseHeaderField As ResponseHeader
        
        Private getReportFieldsOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "https://adwords.google.com/api/adwords/cm/v201209/ReportDefinitionService"
        End Sub
        
        Public Property RequestHeader() As RequestHeader
            Get
                Return Me.requestHeaderField
            End Get
            Set
                Me.requestHeaderField = value
            End Set
        End Property
        
        Public Property ResponseHeader() As ResponseHeader
            Get
                Return Me.responseHeaderField
            End Get
            Set
                Me.responseHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Event getReportFieldsCompleted As getReportFieldsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/cm/v201209", ResponseNamespace:="https://adwords.google.com/api/adwords/cm/v201209", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getReportFields(ByVal reportType As ReportDefinitionReportType, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal reportTypeSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute("rval")> ReportDefinitionField()
            Dim results() As Object = Me.Invoke("getReportFields", New Object() {reportType, reportTypeSpecified})
            Return CType(results(0),ReportDefinitionField())
        End Function
        
        '''<remarks/>
        Public Function BegingetReportFields(ByVal reportType As ReportDefinitionReportType, ByVal reportTypeSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getReportFields", New Object() {reportType, reportTypeSpecified}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetReportFields(ByVal asyncResult As System.IAsyncResult) As ReportDefinitionField()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ReportDefinitionField())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getReportFieldsAsync(ByVal reportType As ReportDefinitionReportType, ByVal reportTypeSpecified As Boolean)
            Me.getReportFieldsAsync(reportType, reportTypeSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getReportFieldsAsync(ByVal reportType As ReportDefinitionReportType, ByVal reportTypeSpecified As Boolean, ByVal userState As Object)
            If (Me.getReportFieldsOperationCompleted Is Nothing) Then
                Me.getReportFieldsOperationCompleted = AddressOf Me.OngetReportFieldsOperationCompleted
            End If
            Me.InvokeAsync("getReportFields", New Object() {reportType, reportTypeSpecified}, Me.getReportFieldsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetReportFieldsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getReportFieldsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getReportFieldsCompleted(Me, New getReportFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201209"),  _
     System.Xml.Serialization.XmlRootAttribute("RequestHeader", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201209", IsNullable:=false)>  _
    Partial Public Class RequestHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private authTokenField As String
        
        Private clientCustomerIdField As String
        
        Private developerTokenField As String
        
        Private userAgentField As String
        
        Private validateOnlyField As Boolean
        
        Private validateOnlyFieldSpecified As Boolean
        
        Private partialFailureField As Boolean
        
        Private partialFailureFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property authToken() As String
            Get
                Return Me.authTokenField
            End Get
            Set
                Me.authTokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property clientCustomerId() As String
            Get
                Return Me.clientCustomerIdField
            End Get
            Set
                Me.clientCustomerIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property developerToken() As String
            Get
                Return Me.developerTokenField
            End Get
            Set
                Me.developerTokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property userAgent() As String
            Get
                Return Me.userAgentField
            End Get
            Set
                Me.userAgentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property validateOnly() As Boolean
            Get
                Return Me.validateOnlyField
            End Get
            Set
                Me.validateOnlyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property validateOnlySpecified() As Boolean
            Get
                Return Me.validateOnlyFieldSpecified
            End Get
            Set
                Me.validateOnlyFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property partialFailure() As Boolean
            Get
                Return Me.partialFailureField
            End Get
            Set
                Me.partialFailureField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property partialFailureSpecified() As Boolean
            Get
                Return Me.partialFailureFieldSpecified
            End Get
            Set
                Me.partialFailureFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201209")>  _
    Partial Public Class EnumValuePair
        
        Private enumValueField As String
        
        Private enumDisplayValueField As String
        
        '''<remarks/>
        Public Property enumValue() As String
            Get
                Return Me.enumValueField
            End Get
            Set
                Me.enumValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property enumDisplayValue() As String
            Get
                Return Me.enumDisplayValueField
            End Get
            Set
                Me.enumDisplayValueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201209")>  _
    Partial Public Class ReportDefinitionField
        
        Private fieldNameField As String
        
        Private displayFieldNameField As String
        
        Private xmlAttributeNameField As String
        
        Private fieldTypeField As String
        
        Private enumValuesField() As String
        
        Private canSelectField As Boolean
        
        Private canSelectFieldSpecified As Boolean
        
        Private canFilterField As Boolean
        
        Private canFilterFieldSpecified As Boolean
        
        Private isEnumTypeField As Boolean
        
        Private isEnumTypeFieldSpecified As Boolean
        
        Private isBetaField As Boolean
        
        Private isBetaFieldSpecified As Boolean
        
        Private enumValuePairsField() As EnumValuePair
        
        '''<remarks/>
        Public Property fieldName() As String
            Get
                Return Me.fieldNameField
            End Get
            Set
                Me.fieldNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property displayFieldName() As String
            Get
                Return Me.displayFieldNameField
            End Get
            Set
                Me.displayFieldNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property xmlAttributeName() As String
            Get
                Return Me.xmlAttributeNameField
            End Get
            Set
                Me.xmlAttributeNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fieldType() As String
            Get
                Return Me.fieldTypeField
            End Get
            Set
                Me.fieldTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("enumValues")>  _
        Public Property enumValues() As String()
            Get
                Return Me.enumValuesField
            End Get
            Set
                Me.enumValuesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property canSelect() As Boolean
            Get
                Return Me.canSelectField
            End Get
            Set
                Me.canSelectField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property canSelectSpecified() As Boolean
            Get
                Return Me.canSelectFieldSpecified
            End Get
            Set
                Me.canSelectFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property canFilter() As Boolean
            Get
                Return Me.canFilterField
            End Get
            Set
                Me.canFilterField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property canFilterSpecified() As Boolean
            Get
                Return Me.canFilterFieldSpecified
            End Get
            Set
                Me.canFilterFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property isEnumType() As Boolean
            Get
                Return Me.isEnumTypeField
            End Get
            Set
                Me.isEnumTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property isEnumTypeSpecified() As Boolean
            Get
                Return Me.isEnumTypeFieldSpecified
            End Get
            Set
                Me.isEnumTypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property isBeta() As Boolean
            Get
                Return Me.isBetaField
            End Get
            Set
                Me.isBetaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property isBetaSpecified() As Boolean
            Get
                Return Me.isBetaFieldSpecified
            End Get
            Set
                Me.isBetaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("enumValuePairs")>  _
        Public Property enumValuePairs() As EnumValuePair()
            Get
                Return Me.enumValuePairsField
            End Get
            Set
                Me.enumValuePairsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201209"),  _
     System.Xml.Serialization.XmlRootAttribute("ResponseHeader", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201209", IsNullable:=false)>  _
    Partial Public Class ResponseHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private requestIdField As String
        
        Private serviceNameField As String
        
        Private methodNameField As String
        
        Private operationsField As Long
        
        Private operationsFieldSpecified As Boolean
        
        Private responseTimeField As Long
        
        Private responseTimeFieldSpecified As Boolean
        
        Private unitsField As Long
        
        Private unitsFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property requestId() As String
            Get
                Return Me.requestIdField
            End Get
            Set
                Me.requestIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property serviceName() As String
            Get
                Return Me.serviceNameField
            End Get
            Set
                Me.serviceNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property methodName() As String
            Get
                Return Me.methodNameField
            End Get
            Set
                Me.methodNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property operations() As Long
            Get
                Return Me.operationsField
            End Get
            Set
                Me.operationsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property operationsSpecified() As Boolean
            Get
                Return Me.operationsFieldSpecified
            End Get
            Set
                Me.operationsFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseTime() As Long
            Get
                Return Me.responseTimeField
            End Get
            Set
                Me.responseTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property responseTimeSpecified() As Boolean
            Get
                Return Me.responseTimeFieldSpecified
            End Get
            Set
                Me.responseTimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property units() As Long
            Get
                Return Me.unitsField
            End Get
            Set
                Me.unitsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property unitsSpecified() As Boolean
            Get
                Return Me.unitsFieldSpecified
            End Get
            Set
                Me.unitsFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ReportDefinition.ReportType", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201209")>  _
    Public Enum ReportDefinitionReportType
        
        '''<remarks/>
        KEYWORDS_PERFORMANCE_REPORT
        
        '''<remarks/>
        AD_PERFORMANCE_REPORT
        
        '''<remarks/>
        URL_PERFORMANCE_REPORT
        
        '''<remarks/>
        ADGROUP_PERFORMANCE_REPORT
        
        '''<remarks/>
        CAMPAIGN_PERFORMANCE_REPORT
        
        '''<remarks/>
        ACCOUNT_PERFORMANCE_REPORT
        
        '''<remarks/>
        GEO_PERFORMANCE_REPORT
        
        '''<remarks/>
        SEARCH_QUERY_PERFORMANCE_REPORT
        
        '''<remarks/>
        MANAGED_PLACEMENTS_PERFORMANCE_REPORT
        
        '''<remarks/>
        AUTOMATIC_PLACEMENTS_PERFORMANCE_REPORT
        
        '''<remarks/>
        CAMPAIGN_NEGATIVE_KEYWORDS_PERFORMANCE_REPORT
        
        '''<remarks/>
        CAMPAIGN_NEGATIVE_PLACEMENTS_PERFORMANCE_REPORT
        
        '''<remarks/>
        AD_EXTENSIONS_PERFORMANCE_REPORT
        
        '''<remarks/>
        DESTINATION_URL_REPORT
        
        '''<remarks/>
        CREATIVE_CONVERSION_REPORT
        
        '''<remarks/>
        CALL_METRICS_CALL_DETAILS_REPORT
        
        '''<remarks/>
        ACCOUNT_REACH_FREQUENCY_REPORT
        
        '''<remarks/>
        CAMPAIGN_REACH_FREQUENCY_REPORT
        
        '''<remarks/>
        ADGROUP_REACH_FREQUENCY_REPORT
        
        '''<remarks/>
        CRITERIA_PERFORMANCE_REPORT
        
        '''<remarks/>
        CLICK_PERFORMANCE_REPORT
        
        '''<remarks/>
        DISPLAY_KEYWORD_PERFORMANCE_REPORT
        
        '''<remarks/>
        UNKNOWN
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub getReportFieldsCompletedEventHandler(ByVal sender As Object, ByVal e As getReportFieldsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getReportFieldsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ReportDefinitionField()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ReportDefinitionField())
            End Get
        End Property
    End Class
End Namespace
