'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'
Namespace GoogleWebServicesV201003
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="ReportDefinitionServiceSoapBinding", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201003"), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Operation))> _
    Partial Public Class ReportDefinitionService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private requestHeaderField As RequestHeader

        Private responseHeaderField As ResponseHeader

        Private getOperationCompleted As System.Threading.SendOrPostCallback

        Private getReportFieldsOperationCompleted As System.Threading.SendOrPostCallback

        Private mutateOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = "https://adwords.google.com/api/adwords/cm/v201003/ReportDefinitionService"
        End Sub

        Public Property RequestHeader() As RequestHeader
            Get
                Return Me.requestHeaderField
            End Get
            Set(ByVal value As RequestHeader)
                Me.requestHeaderField = Value
            End Set
        End Property

        Public Property ResponseHeader() As ResponseHeader
            Get
                Return Me.responseHeaderField
            End Get
            Set(ByVal value As ResponseHeader)
                Me.responseHeaderField = Value
            End Set
        End Property

        '''<remarks/>
        Public Event getCompleted As getCompletedEventHandler

        '''<remarks/>
        Public Event getReportFieldsCompleted As getReportFieldsCompletedEventHandler

        '''<remarks/>
        Public Event mutateCompleted As mutateCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/cm/v201003", ResponseNamespace:="https://adwords.google.com/api/adwords/cm/v201003", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function [get](ByVal selector As ReportDefinitionSelector) As <System.Xml.Serialization.XmlElementAttribute("rval")> ReportDefinitionPage
            Dim results() As Object = Me.Invoke("get", New Object() {selector})
            Return CType(results(0), ReportDefinitionPage)
        End Function

        '''<remarks/>
        Public Function Beginget(ByVal selector As ReportDefinitionSelector, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("get", New Object() {selector}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function Endget(ByVal asyncResult As System.IAsyncResult) As ReportDefinitionPage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), ReportDefinitionPage)
        End Function

        '''<remarks/>
        Public Overloads Sub getAsync(ByVal selector As ReportDefinitionSelector)
            Me.getAsync(selector, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getAsync(ByVal selector As ReportDefinitionSelector, ByVal userState As Object)
            If (Me.getOperationCompleted Is Nothing) Then
                Me.getOperationCompleted = AddressOf Me.OngetOperationCompleted
            End If
            Me.InvokeAsync("get", New Object() {selector}, Me.getOperationCompleted, userState)
        End Sub

        Private Sub OngetOperationCompleted(ByVal arg As Object)
            If (Not (Me.getCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getCompleted(Me, New getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/cm/v201003", ResponseNamespace:="https://adwords.google.com/api/adwords/cm/v201003", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getReportFields(ByVal reportType As ReportDefinitionReportType, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal reportTypeSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute("rval")> ReportDefinitionField()
            Dim results() As Object = Me.Invoke("getReportFields", New Object() {reportType, reportTypeSpecified})
            Return CType(results(0), ReportDefinitionField())
        End Function

        '''<remarks/>
        Public Function BegingetReportFields(ByVal reportType As ReportDefinitionReportType, ByVal reportTypeSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getReportFields", New Object() {reportType, reportTypeSpecified}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetReportFields(ByVal asyncResult As System.IAsyncResult) As ReportDefinitionField()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), ReportDefinitionField())
        End Function

        '''<remarks/>
        Public Overloads Sub getReportFieldsAsync(ByVal reportType As ReportDefinitionReportType, ByVal reportTypeSpecified As Boolean)
            Me.getReportFieldsAsync(reportType, reportTypeSpecified, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getReportFieldsAsync(ByVal reportType As ReportDefinitionReportType, ByVal reportTypeSpecified As Boolean, ByVal userState As Object)
            If (Me.getReportFieldsOperationCompleted Is Nothing) Then
                Me.getReportFieldsOperationCompleted = AddressOf Me.OngetReportFieldsOperationCompleted
            End If
            Me.InvokeAsync("getReportFields", New Object() {reportType, reportTypeSpecified}, Me.getReportFieldsOperationCompleted, userState)
        End Sub

        Private Sub OngetReportFieldsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getReportFieldsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getReportFieldsCompleted(Me, New getReportFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/cm/v201003", ResponseNamespace:="https://adwords.google.com/api/adwords/cm/v201003", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function mutate(<System.Xml.Serialization.XmlElementAttribute("operations")> ByVal operations() As ReportDefinitionOperation) As <System.Xml.Serialization.XmlElementAttribute("rval")> ReportDefinition()
            Dim results() As Object = Me.Invoke("mutate", New Object() {operations})
            Return CType(results(0), ReportDefinition())
        End Function

        '''<remarks/>
        Public Function Beginmutate(ByVal operations() As ReportDefinitionOperation, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("mutate", New Object() {operations}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function Endmutate(ByVal asyncResult As System.IAsyncResult) As ReportDefinition()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), ReportDefinition())
        End Function

        '''<remarks/>
        Public Overloads Sub mutateAsync(ByVal operations() As ReportDefinitionOperation)
            Me.mutateAsync(operations, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub mutateAsync(ByVal operations() As ReportDefinitionOperation, ByVal userState As Object)
            If (Me.mutateOperationCompleted Is Nothing) Then
                Me.mutateOperationCompleted = AddressOf Me.OnmutateOperationCompleted
            End If
            Me.InvokeAsync("mutate", New Object() {operations}, Me.mutateOperationCompleted, userState)
        End Sub

        Private Sub OnmutateOperationCompleted(ByVal arg As Object)
            If (Not (Me.mutateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent mutateCompleted(Me, New mutateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003"), _
     System.Xml.Serialization.XmlRootAttribute("RequestHeader", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201003", IsNullable:=False)> _
    Partial Public Class RequestHeader
        Inherits System.Web.Services.Protocols.SoapHeader

        Private authTokenField As String

        Private clientCustomerIdField As String

        Private clientEmailField As String

        Private developerTokenField As String

        Private userAgentField As String

        Private validateOnlyField As Boolean

        Private validateOnlyFieldSpecified As Boolean

        '''<remarks/>
        Public Property authToken() As String
            Get
                Return Me.authTokenField
            End Get
            Set(ByVal value As String)
                Me.authTokenField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property clientCustomerId() As String
            Get
                Return Me.clientCustomerIdField
            End Get
            Set(ByVal value As String)
                Me.clientCustomerIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property clientEmail() As String
            Get
                Return Me.clientEmailField
            End Get
            Set(ByVal value As String)
                Me.clientEmailField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property developerToken() As String
            Get
                Return Me.developerTokenField
            End Get
            Set(ByVal value As String)
                Me.developerTokenField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property userAgent() As String
            Get
                Return Me.userAgentField
            End Get
            Set(ByVal value As String)
                Me.userAgentField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property validateOnly() As Boolean
            Get
                Return Me.validateOnlyField
            End Get
            Set(ByVal value As Boolean)
                Me.validateOnlyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property validateOnlySpecified() As Boolean
            Get
                Return Me.validateOnlyFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.validateOnlyFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ReportDefinitionOperation)), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public MustInherit Class Operation

        Private operatorField As [Operator]

        Private operatorFieldSpecified As Boolean

        Private operationTypeField As String

        '''<remarks/>
        Public Property [operator]() As [Operator]
            Get
                Return Me.operatorField
            End Get
            Set(ByVal value As [Operator])
                Me.operatorField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property operatorSpecified() As Boolean
            Get
                Return Me.operatorFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.operatorFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Operation.Type")> _
        Public Property OperationType() As String
            Get
                Return Me.operationTypeField
            End Get
            Set(ByVal value As String)
                Me.operationTypeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Public Enum [Operator]

        '''<remarks/>
        ADD

        '''<remarks/>
        REMOVE

        '''<remarks/>
        [SET]
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public Class ReportDefinitionOperation
        Inherits Operation

        Private operandField As ReportDefinition

        '''<remarks/>
        Public Property operand() As ReportDefinition
            Get
                Return Me.operandField
            End Get
            Set(ByVal value As ReportDefinition)
                Me.operandField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public Class ReportDefinition

        Private idField As Long

        Private idFieldSpecified As Boolean

        Private selectorField As Selector

        Private reportNameField As String

        Private reportTypeField As ReportDefinitionReportType

        Private reportTypeFieldSpecified As Boolean

        Private hasAttachmentField As Boolean

        Private hasAttachmentFieldSpecified As Boolean

        Private dateRangeTypeField As ReportDefinitionDateRangeType

        Private dateRangeTypeFieldSpecified As Boolean

        Private downloadFormatField As DownloadFormat

        Private downloadFormatFieldSpecified As Boolean

        Private creationTimeField As String

        '''<remarks/>
        Public Property id() As Long
            Get
                Return Me.idField
            End Get
            Set(ByVal value As Long)
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property idSpecified() As Boolean
            Get
                Return Me.idFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.idFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property selector() As Selector
            Get
                Return Me.selectorField
            End Get
            Set(ByVal value As Selector)
                Me.selectorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property reportName() As String
            Get
                Return Me.reportNameField
            End Get
            Set(ByVal value As String)
                Me.reportNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property reportType() As ReportDefinitionReportType
            Get
                Return Me.reportTypeField
            End Get
            Set(ByVal value As ReportDefinitionReportType)
                Me.reportTypeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property reportTypeSpecified() As Boolean
            Get
                Return Me.reportTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.reportTypeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property hasAttachment() As Boolean
            Get
                Return Me.hasAttachmentField
            End Get
            Set(ByVal value As Boolean)
                Me.hasAttachmentField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property hasAttachmentSpecified() As Boolean
            Get
                Return Me.hasAttachmentFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.hasAttachmentFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property dateRangeType() As ReportDefinitionDateRangeType
            Get
                Return Me.dateRangeTypeField
            End Get
            Set(ByVal value As ReportDefinitionDateRangeType)
                Me.dateRangeTypeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dateRangeTypeSpecified() As Boolean
            Get
                Return Me.dateRangeTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dateRangeTypeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property downloadFormat() As DownloadFormat
            Get
                Return Me.downloadFormatField
            End Get
            Set(ByVal value As DownloadFormat)
                Me.downloadFormatField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property downloadFormatSpecified() As Boolean
            Get
                Return Me.downloadFormatFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.downloadFormatFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property creationTime() As String
            Get
                Return Me.creationTimeField
            End Get
            Set(ByVal value As String)
                Me.creationTimeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public Class Selector

        Private fieldsField() As String

        Private predicatesField() As Predicate

        Private dateRangeField As DateRange

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("fields")> _
        Public Property fields() As String()
            Get
                Return Me.fieldsField
            End Get
            Set(ByVal value As String())
                Me.fieldsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("predicates")> _
        Public Property predicates() As Predicate()
            Get
                Return Me.predicatesField
            End Get
            Set(ByVal value As Predicate())
                Me.predicatesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property dateRange() As DateRange
            Get
                Return Me.dateRangeField
            End Get
            Set(ByVal value As DateRange)
                Me.dateRangeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public Class Predicate

        Private fieldField As String

        Private operatorField As PredicateOperator

        Private operatorFieldSpecified As Boolean

        Private valuesField() As String

        '''<remarks/>
        Public Property field() As String
            Get
                Return Me.fieldField
            End Get
            Set(ByVal value As String)
                Me.fieldField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [operator]() As PredicateOperator
            Get
                Return Me.operatorField
            End Get
            Set(ByVal value As PredicateOperator)
                Me.operatorField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property operatorSpecified() As Boolean
            Get
                Return Me.operatorFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.operatorFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("values")> _
        Public Property values() As String()
            Get
                Return Me.valuesField
            End Get
            Set(ByVal value As String())
                Me.valuesField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="Predicate.Operator", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Public Enum PredicateOperator

        '''<remarks/>
        EQUALS

        '''<remarks/>
        NOT_EQUALS

        '''<remarks/>
        [IN]

        '''<remarks/>
        NOT_IN

        '''<remarks/>
        GREATER_THAN

        '''<remarks/>
        GREATER_THAN_EQUALS

        '''<remarks/>
        LESS_THAN

        '''<remarks/>
        LESS_THAN_EQUALS

        '''<remarks/>
        STARTS_WITH

        '''<remarks/>
        STARTS_WITH_IGNORE_CASE

        '''<remarks/>
        CONTAINS

        '''<remarks/>
        CONTAINS_IGNORE_CASE

        '''<remarks/>
        DOES_NOT_CONTAIN

        '''<remarks/>
        DOES_NOT_CONTAIN_IGNORE_CASE

        '''<remarks/>
        UNKNOWN
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public Class DateRange

        Private minField As String

        Private maxField As String

        '''<remarks/>
        Public Property min() As String
            Get
                Return Me.minField
            End Get
            Set(ByVal value As String)
                Me.minField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property max() As String
            Get
                Return Me.maxField
            End Get
            Set(ByVal value As String)
                Me.maxField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ReportDefinition.ReportType", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Public Enum ReportDefinitionReportType

        '''<remarks/>
        KEYWORDS_PERFORMANCE_REPORT

        '''<remarks/>
        AD_PERFORMANCE_REPORT

        '''<remarks/>
        URL_PERFORMANCE_REPORT

        '''<remarks/>
        ADGROUP_PERFORMANCE_REPORT

        '''<remarks/>
        CAMPAIGN_PERFORMANCE_REPORT

        '''<remarks/>
        SEARCH_QUERY_PERFORMANCE_REPORT

        '''<remarks/>
        MANAGED_PLACEMENTS_PERFORMANCE_REPORT

        '''<remarks/>
        AUTOMATIC_PLACEMENTS_PERFORMANCE_REPORT

        '''<remarks/>
        ADGROUP_NEGATIVE_KEYWORDS_PERFORMANCE_REPORT

        '''<remarks/>
        CAMPAIGN_NEGATIVE_KEYWORDS_PERFORMANCE_REPORT

        '''<remarks/>
        ADGROUP_NEGATIVE_PLACEMENTS_PERFORMANCE_REPORT

        '''<remarks/>
        CAMPAIGN_NEGATIVE_PLACEMENTS_PERFORMANCE_REPORT
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="ReportDefinition.DateRangeType", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Public Enum ReportDefinitionDateRangeType

        '''<remarks/>
        TODAY

        '''<remarks/>
        YESTERDAY

        '''<remarks/>
        LAST_7_DAYS

        '''<remarks/>
        LAST_WEEK

        '''<remarks/>
        LAST_BUSINESS_WEEK

        '''<remarks/>
        THIS_MONTH

        '''<remarks/>
        LAST_MONTH

        '''<remarks/>
        ALL_TIME

        '''<remarks/>
        CUSTOM_DATE
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Public Enum DownloadFormat

        '''<remarks/>
        CSVFOREXCEL

        '''<remarks/>
        CSV

        '''<remarks/>
        TSV

        '''<remarks/>
        XML

        '''<remarks/>
        GZIPPED_CSV
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public Class ReportDefinitionField

        Private fieldNameField As String

        Private fieldTypeField As String

        Private enumValuesField() As String

        Private canSelectField As Boolean

        Private canSelectFieldSpecified As Boolean

        Private canFilterField As Boolean

        Private canFilterFieldSpecified As Boolean

        '''<remarks/>
        Public Property fieldName() As String
            Get
                Return Me.fieldNameField
            End Get
            Set(ByVal value As String)
                Me.fieldNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property fieldType() As String
            Get
                Return Me.fieldTypeField
            End Get
            Set(ByVal value As String)
                Me.fieldTypeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("enumValues")> _
        Public Property enumValues() As String()
            Get
                Return Me.enumValuesField
            End Get
            Set(ByVal value As String())
                Me.enumValuesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property canSelect() As Boolean
            Get
                Return Me.canSelectField
            End Get
            Set(ByVal value As Boolean)
                Me.canSelectField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property canSelectSpecified() As Boolean
            Get
                Return Me.canSelectFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.canSelectFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property canFilter() As Boolean
            Get
                Return Me.canFilterField
            End Get
            Set(ByVal value As Boolean)
                Me.canFilterField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property canFilterSpecified() As Boolean
            Get
                Return Me.canFilterFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.canFilterFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public Class ReportDefinitionPage

        Private entriesField() As ReportDefinition

        Private totalNumEntriesField As Integer

        Private totalNumEntriesFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("entries")> _
        Public Property entries() As ReportDefinition()
            Get
                Return Me.entriesField
            End Get
            Set(ByVal value As ReportDefinition())
                Me.entriesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property totalNumEntries() As Integer
            Get
                Return Me.totalNumEntriesField
            End Get
            Set(ByVal value As Integer)
                Me.totalNumEntriesField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property totalNumEntriesSpecified() As Boolean
            Get
                Return Me.totalNumEntriesFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.totalNumEntriesFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public Class Paging

        Private startIndexField As Integer

        Private startIndexFieldSpecified As Boolean

        Private numberResultsField As Integer

        Private numberResultsFieldSpecified As Boolean

        '''<remarks/>
        Public Property startIndex() As Integer
            Get
                Return Me.startIndexField
            End Get
            Set(ByVal value As Integer)
                Me.startIndexField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property startIndexSpecified() As Boolean
            Get
                Return Me.startIndexFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.startIndexFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property numberResults() As Integer
            Get
                Return Me.numberResultsField
            End Get
            Set(ByVal value As Integer)
                Me.numberResultsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property numberResultsSpecified() As Boolean
            Get
                Return Me.numberResultsFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.numberResultsFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003")> _
    Partial Public Class ReportDefinitionSelector

        Private pagingField As Paging

        '''<remarks/>
        Public Property paging() As Paging
            Get
                Return Me.pagingField
            End Get
            Set(ByVal value As Paging)
                Me.pagingField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/cm/v201003"), _
     System.Xml.Serialization.XmlRootAttribute("ResponseHeader", [Namespace]:="https://adwords.google.com/api/adwords/cm/v201003", IsNullable:=False)> _
    Partial Public Class ResponseHeader
        Inherits System.Web.Services.Protocols.SoapHeader

        Private requestIdField As String

        Private operationsField As Long

        Private operationsFieldSpecified As Boolean

        Private responseTimeField As Long

        Private responseTimeFieldSpecified As Boolean

        Private unitsField As Long

        Private unitsFieldSpecified As Boolean

        '''<remarks/>
        Public Property requestId() As String
            Get
                Return Me.requestIdField
            End Get
            Set(ByVal value As String)
                Me.requestIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property operations() As Long
            Get
                Return Me.operationsField
            End Get
            Set(ByVal value As Long)
                Me.operationsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property operationsSpecified() As Boolean
            Get
                Return Me.operationsFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.operationsFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property responseTime() As Long
            Get
                Return Me.responseTimeField
            End Get
            Set(ByVal value As Long)
                Me.responseTimeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property responseTimeSpecified() As Boolean
            Get
                Return Me.responseTimeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.responseTimeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property units() As Long
            Get
                Return Me.unitsField
            End Get
            Set(ByVal value As Long)
                Me.unitsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property unitsSpecified() As Boolean
            Get
                Return Me.unitsFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.unitsFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getCompletedEventHandler(ByVal sender As Object, ByVal e As getCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As ReportDefinitionPage
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), ReportDefinitionPage)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getReportFieldsCompletedEventHandler(ByVal sender As Object, ByVal e As getReportFieldsCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getReportFieldsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As ReportDefinitionField()
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), ReportDefinitionField())
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub mutateCompletedEventHandler(ByVal sender As Object, ByVal e As mutateCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class mutateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As ReportDefinition()
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), ReportDefinition())
            End Get
        End Property
    End Class
End Namespace
