'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

Namespace GoogleWebServicesV10

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="ReportServiceSoapBinding", [Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public Class ReportService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private useragentValueField As useragent

        Private passwordValueField As password

        Private emailValueField As email

        Private clientEmailValueField As clientEmail

        Private clientCustomerIdValueField As clientCustomerId

        Private developerTokenValueField As developerToken

        Private applicationTokenValueField As applicationToken

        Private responseTimeValueField As responseTime

        Private operationsValueField As operations

        Private unitsValueField As units

        Private requestIdValueField As requestId

        Private deleteReportOperationCompleted As System.Threading.SendOrPostCallback

        Private getAllJobsOperationCompleted As System.Threading.SendOrPostCallback

        Private getGzipReportDownloadUrlOperationCompleted As System.Threading.SendOrPostCallback

        Private getReportDownloadUrlOperationCompleted As System.Threading.SendOrPostCallback

        Private getReportJobStatusOperationCompleted As System.Threading.SendOrPostCallback

        Private scheduleReportJobOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = "https://adwords.google.com/api/adwords/v10/ReportService"
        End Sub

        Public Property useragentValue() As useragent
            Get
                Return Me.useragentValueField
            End Get
            Set(ByVal value As useragent)
                Me.useragentValueField = value
            End Set
        End Property

        Public Property passwordValue() As password
            Get
                Return Me.passwordValueField
            End Get
            Set(ByVal value As password)
                Me.passwordValueField = value
            End Set
        End Property

        Public Property emailValue() As email
            Get
                Return Me.emailValueField
            End Get
            Set(ByVal value As email)
                Me.emailValueField = value
            End Set
        End Property

        Public Property clientEmailValue() As clientEmail
            Get
                Return Me.clientEmailValueField
            End Get
            Set(ByVal value As clientEmail)
                Me.clientEmailValueField = value
            End Set
        End Property

        Public Property clientCustomerIdValue() As clientCustomerId
            Get
                Return Me.clientCustomerIdValueField
            End Get
            Set(ByVal value As clientCustomerId)
                Me.clientCustomerIdValueField = value
            End Set
        End Property

        Public Property developerTokenValue() As developerToken
            Get
                Return Me.developerTokenValueField
            End Get
            Set(ByVal value As developerToken)
                Me.developerTokenValueField = value
            End Set
        End Property

        Public Property applicationTokenValue() As applicationToken
            Get
                Return Me.applicationTokenValueField
            End Get
            Set(ByVal value As applicationToken)
                Me.applicationTokenValueField = value
            End Set
        End Property

        Public Property responseTimeValue() As responseTime
            Get
                Return Me.responseTimeValueField
            End Get
            Set(ByVal value As responseTime)
                Me.responseTimeValueField = value
            End Set
        End Property

        Public Property operationsValue() As operations
            Get
                Return Me.operationsValueField
            End Get
            Set(ByVal value As operations)
                Me.operationsValueField = value
            End Set
        End Property

        Public Property unitsValue() As units
            Get
                Return Me.unitsValueField
            End Get
            Set(ByVal value As units)
                Me.unitsValueField = value
            End Set
        End Property

        Public Property requestIdValue() As requestId
            Get
                Return Me.requestIdValueField
            End Get
            Set(ByVal value As requestId)
                Me.requestIdValueField = value
            End Set
        End Property

        '''<remarks/>
        Public Event deleteReportCompleted As deleteReportCompletedEventHandler

        '''<remarks/>
        Public Event getAllJobsCompleted As getAllJobsCompletedEventHandler

        '''<remarks/>
        Public Event getGzipReportDownloadUrlCompleted As getGzipReportDownloadUrlCompletedEventHandler

        '''<remarks/>
        Public Event getReportDownloadUrlCompleted As getReportDownloadUrlCompletedEventHandler

        '''<remarks/>
        Public Event getReportJobStatusCompleted As getReportJobStatusCompletedEventHandler

        '''<remarks/>
        Public Event scheduleReportJobCompleted As scheduleReportJobCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("emailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/v10", ResponseNamespace:="https://adwords.google.com/api/adwords/v10", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Sub deleteReport(ByVal reportJobId As Long)
            Me.Invoke("deleteReport", New Object() {reportJobId})
        End Sub

        '''<remarks/>
        Public Function BegindeleteReport(ByVal reportJobId As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("deleteReport", New Object() {reportJobId}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Sub EnddeleteReport(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub

        '''<remarks/>
        Public Overloads Sub deleteReportAsync(ByVal reportJobId As Long)
            Me.deleteReportAsync(reportJobId, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub deleteReportAsync(ByVal reportJobId As Long, ByVal userState As Object)
            If (Me.deleteReportOperationCompleted Is Nothing) Then
                Me.deleteReportOperationCompleted = AddressOf Me.OndeleteReportOperationCompleted
            End If
            Me.InvokeAsync("deleteReport", New Object() {reportJobId}, Me.deleteReportOperationCompleted, userState)
        End Sub

        Private Sub OndeleteReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.deleteReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent deleteReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("emailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/v10", ResponseNamespace:="https://adwords.google.com/api/adwords/v10", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getAllJobs() As <System.Xml.Serialization.XmlElementAttribute("getAllJobsReturn")> ReportJob()
            Dim results() As Object = Me.Invoke("getAllJobs", New Object(-1) {})
            Return CType(results(0), ReportJob())
        End Function

        '''<remarks/>
        Public Function BegingetAllJobs(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getAllJobs", New Object(-1) {}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetAllJobs(ByVal asyncResult As System.IAsyncResult) As ReportJob()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), ReportJob())
        End Function

        '''<remarks/>
        Public Overloads Sub getAllJobsAsync()
            Me.getAllJobsAsync(Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getAllJobsAsync(ByVal userState As Object)
            If (Me.getAllJobsOperationCompleted Is Nothing) Then
                Me.getAllJobsOperationCompleted = AddressOf Me.OngetAllJobsOperationCompleted
            End If
            Me.InvokeAsync("getAllJobs", New Object(-1) {}, Me.getAllJobsOperationCompleted, userState)
        End Sub

        Private Sub OngetAllJobsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getAllJobsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getAllJobsCompleted(Me, New getAllJobsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("emailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/v10", ResponseNamespace:="https://adwords.google.com/api/adwords/v10", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getGzipReportDownloadUrl(ByVal reportJobId As Long) As <System.Xml.Serialization.XmlElementAttribute("getGzipReportDownloadUrlReturn")> String
            Dim results() As Object = Me.Invoke("getGzipReportDownloadUrl", New Object() {reportJobId})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Function BegingetGzipReportDownloadUrl(ByVal reportJobId As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getGzipReportDownloadUrl", New Object() {reportJobId}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetGzipReportDownloadUrl(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub getGzipReportDownloadUrlAsync(ByVal reportJobId As Long)
            Me.getGzipReportDownloadUrlAsync(reportJobId, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getGzipReportDownloadUrlAsync(ByVal reportJobId As Long, ByVal userState As Object)
            If (Me.getGzipReportDownloadUrlOperationCompleted Is Nothing) Then
                Me.getGzipReportDownloadUrlOperationCompleted = AddressOf Me.OngetGzipReportDownloadUrlOperationCompleted
            End If
            Me.InvokeAsync("getGzipReportDownloadUrl", New Object() {reportJobId}, Me.getGzipReportDownloadUrlOperationCompleted, userState)
        End Sub

        Private Sub OngetGzipReportDownloadUrlOperationCompleted(ByVal arg As Object)
            If (Not (Me.getGzipReportDownloadUrlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getGzipReportDownloadUrlCompleted(Me, New getGzipReportDownloadUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("emailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/v10", ResponseNamespace:="https://adwords.google.com/api/adwords/v10", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getReportDownloadUrl(ByVal reportJobId As Long) As <System.Xml.Serialization.XmlElementAttribute("getReportDownloadUrlReturn")> String
            Dim results() As Object = Me.Invoke("getReportDownloadUrl", New Object() {reportJobId})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Function BegingetReportDownloadUrl(ByVal reportJobId As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getReportDownloadUrl", New Object() {reportJobId}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetReportDownloadUrl(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub getReportDownloadUrlAsync(ByVal reportJobId As Long)
            Me.getReportDownloadUrlAsync(reportJobId, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getReportDownloadUrlAsync(ByVal reportJobId As Long, ByVal userState As Object)
            If (Me.getReportDownloadUrlOperationCompleted Is Nothing) Then
                Me.getReportDownloadUrlOperationCompleted = AddressOf Me.OngetReportDownloadUrlOperationCompleted
            End If
            Me.InvokeAsync("getReportDownloadUrl", New Object() {reportJobId}, Me.getReportDownloadUrlOperationCompleted, userState)
        End Sub

        Private Sub OngetReportDownloadUrlOperationCompleted(ByVal arg As Object)
            If (Not (Me.getReportDownloadUrlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getReportDownloadUrlCompleted(Me, New getReportDownloadUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("emailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/v10", ResponseNamespace:="https://adwords.google.com/api/adwords/v10", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getReportJobStatus(ByVal reportJobId As Long) As <System.Xml.Serialization.XmlElementAttribute("getReportJobStatusReturn")> ReportJobStatus
            Dim results() As Object = Me.Invoke("getReportJobStatus", New Object() {reportJobId})
            Return CType(results(0), ReportJobStatus)
        End Function

        '''<remarks/>
        Public Function BegingetReportJobStatus(ByVal reportJobId As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getReportJobStatus", New Object() {reportJobId}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetReportJobStatus(ByVal asyncResult As System.IAsyncResult) As ReportJobStatus
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), ReportJobStatus)
        End Function

        '''<remarks/>
        Public Overloads Sub getReportJobStatusAsync(ByVal reportJobId As Long)
            Me.getReportJobStatusAsync(reportJobId, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getReportJobStatusAsync(ByVal reportJobId As Long, ByVal userState As Object)
            If (Me.getReportJobStatusOperationCompleted Is Nothing) Then
                Me.getReportJobStatusOperationCompleted = AddressOf Me.OngetReportJobStatusOperationCompleted
            End If
            Me.InvokeAsync("getReportJobStatus", New Object() {reportJobId}, Me.getReportJobStatusOperationCompleted, userState)
        End Sub

        Private Sub OngetReportJobStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.getReportJobStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getReportJobStatusCompleted(Me, New getReportJobStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("emailValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.Out), _
         System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://adwords.google.com/api/adwords/v10", ResponseNamespace:="https://adwords.google.com/api/adwords/v10", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function scheduleReportJob(ByVal job As ReportJob) As <System.Xml.Serialization.XmlElementAttribute("scheduleReportJobReturn")> Long
            Dim results() As Object = Me.Invoke("scheduleReportJob", New Object() {job})
            Return CType(results(0), Long)
        End Function

        '''<remarks/>
        Public Function BeginscheduleReportJob(ByVal job As ReportJob, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("scheduleReportJob", New Object() {job}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndscheduleReportJob(ByVal asyncResult As System.IAsyncResult) As Long
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), Long)
        End Function

        '''<remarks/>
        Public Overloads Sub scheduleReportJobAsync(ByVal job As ReportJob)
            Me.scheduleReportJobAsync(job, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub scheduleReportJobAsync(ByVal job As ReportJob, ByVal userState As Object)
            If (Me.scheduleReportJobOperationCompleted Is Nothing) Then
                Me.scheduleReportJobOperationCompleted = AddressOf Me.OnscheduleReportJobOperationCompleted
            End If
            Me.InvokeAsync("scheduleReportJob", New Object() {job}, Me.scheduleReportJobOperationCompleted, userState)
        End Sub

        Private Sub OnscheduleReportJobOperationCompleted(ByVal arg As Object)
            If (Not (Me.scheduleReportJobCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent scheduleReportJobCompleted(Me, New scheduleReportJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class clientEmail
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class clientCustomerId
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class useragent
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class developerToken
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class password
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class requestId
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class email
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class operations
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class responseTime
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class units
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10", IsNullable:=False)> _
    Partial Public Class applicationToken
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(UrlReportJob)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(KeywordReportJob)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CustomReportJob)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CampaignReportJob)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AdTextReportJob)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AdImageReportJob)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AdGroupReportJob)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AccountReportJob)), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public MustInherit Class ReportJob

        Private aggregationTypeField As AggregationType

        Private aggregationTypeFieldSpecified As Boolean

        Private clientEmailsField() As String

        Private crossClientField As Boolean

        Private crossClientFieldSpecified As Boolean

        Private endDayField As Date

        Private idField As Long

        Private idFieldSpecified As Boolean

        Private nameField As String

        Private startDayField As Date

        Private statusField As ReportJobStatus

        Private statusFieldSpecified As Boolean

        '''<remarks/>
        Public Property aggregationType() As AggregationType
            Get
                Return Me.aggregationTypeField
            End Get
            Set(ByVal value As AggregationType)
                Me.aggregationTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property aggregationTypeSpecified() As Boolean
            Get
                Return Me.aggregationTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.aggregationTypeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("clientEmails")> _
        Public Property clientEmails() As String()
            Get
                Return Me.clientEmailsField
            End Get
            Set(ByVal value As String())
                Me.clientEmailsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property crossClient() As Boolean
            Get
                Return Me.crossClientField
            End Get
            Set(ByVal value As Boolean)
                Me.crossClientField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property crossClientSpecified() As Boolean
            Get
                Return Me.crossClientFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.crossClientFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property endDay() As Date
            Get
                Return Me.endDayField
            End Get
            Set(ByVal value As Date)
                Me.endDayField = value
            End Set
        End Property

        '''<remarks/>
        Public Property id() As Long
            Get
                Return Me.idField
            End Get
            Set(ByVal value As Long)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property idSpecified() As Boolean
            Get
                Return Me.idFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.idFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property startDay() As Date
            Get
                Return Me.startDayField
            End Get
            Set(ByVal value As Date)
                Me.startDayField = value
            End Set
        End Property

        '''<remarks/>
        Public Property status() As ReportJobStatus
            Get
                Return Me.statusField
            End Get
            Set(ByVal value As ReportJobStatus)
                Me.statusField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.statusFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Public Enum AggregationType

        '''<remarks/>
        Summary

        '''<remarks/>
        Daily

        '''<remarks/>
        Monthly

        '''<remarks/>
        Quarterly

        '''<remarks/>
        Yearly

        '''<remarks/>
        HourlyRegardlessDate

        '''<remarks/>
        HourlyByDate

        '''<remarks/>
        Weekly
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Public Enum ReportJobStatus

        '''<remarks/>
        Pending

        '''<remarks/>
        InProgress

        '''<remarks/>
        Completed

        '''<remarks/>
        Failed
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public Class UrlReportJob
        Inherits ReportJob

        Private adWordsTypeField As AdWordsType

        Private adWordsTypeFieldSpecified As Boolean

        Private campaignsField() As Integer

        '''<remarks/>
        Public Property adWordsType() As AdWordsType
            Get
                Return Me.adWordsTypeField
            End Get
            Set(ByVal value As AdWordsType)
                Me.adWordsTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property adWordsTypeSpecified() As Boolean
            Get
                Return Me.adWordsTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.adWordsTypeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("campaigns")> _
        Public Property campaigns() As Integer()
            Get
                Return Me.campaignsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Public Enum AdWordsType

        '''<remarks/>
        SearchOnly

        '''<remarks/>
        ContentOnly
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public Class KeywordReportJob
        Inherits ReportJob

        Private adWordsTypeField As AdWordsType

        Private adWordsTypeFieldSpecified As Boolean

        Private campaignsField() As Integer

        Private includeZeroImpressionField As Boolean

        Private includeZeroImpressionFieldSpecified As Boolean

        Private keywordStatusesField() As KeywordStatus

        Private keywordTypeField As KeywordType

        Private keywordTypeFieldSpecified As Boolean

        '''<remarks/>
        Public Property adWordsType() As AdWordsType
            Get
                Return Me.adWordsTypeField
            End Get
            Set(ByVal value As AdWordsType)
                Me.adWordsTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property adWordsTypeSpecified() As Boolean
            Get
                Return Me.adWordsTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.adWordsTypeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("campaigns")> _
        Public Property campaigns() As Integer()
            Get
                Return Me.campaignsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property includeZeroImpression() As Boolean
            Get
                Return Me.includeZeroImpressionField
            End Get
            Set(ByVal value As Boolean)
                Me.includeZeroImpressionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property includeZeroImpressionSpecified() As Boolean
            Get
                Return Me.includeZeroImpressionFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.includeZeroImpressionFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("keywordStatuses")> _
        Public Property keywordStatuses() As KeywordStatus()
            Get
                Return Me.keywordStatusesField
            End Get
            Set(ByVal value As KeywordStatus())
                Me.keywordStatusesField = value
            End Set
        End Property

        '''<remarks/>
        Public Property keywordType() As KeywordType
            Get
                Return Me.keywordTypeField
            End Get
            Set(ByVal value As KeywordType)
                Me.keywordTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property keywordTypeSpecified() As Boolean
            Get
                Return Me.keywordTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.keywordTypeFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Public Enum KeywordStatus

        '''<remarks/>
        Disapproved

        '''<remarks/>
        Deleted

        '''<remarks/>
        Paused

        '''<remarks/>
        Active

        '''<remarks/>
        InActive
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Public Enum KeywordType

        '''<remarks/>
        Broad

        '''<remarks/>
        Phrase

        '''<remarks/>
        Exact
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public Class CustomReportJob
        Inherits ReportJob

        Private adGroupStatusesField() As AdGroupStatus

        Private adGroupsField() As Integer

        Private adWordsTypeField As AdWordsType

        Private adWordsTypeFieldSpecified As Boolean

        Private campaignStatusesField() As CampaignStatus

        Private campaignsField() As Integer

        Private customOptionsField() As CustomReportOption

        Private includeZeroImpressionField As Boolean

        Private includeZeroImpressionFieldSpecified As Boolean

        Private keywordStatusesField() As KeywordStatus

        Private keywordTypeField As KeywordType

        Private keywordTypeFieldSpecified As Boolean

        Private keywordsField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("adGroupStatuses")> _
        Public Property adGroupStatuses() As AdGroupStatus()
            Get
                Return Me.adGroupStatusesField
            End Get
            Set(ByVal value As AdGroupStatus())
                Me.adGroupStatusesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("adGroups")> _
        Public Property adGroups() As Integer()
            Get
                Return Me.adGroupsField
            End Get
            Set(ByVal value As Integer())
                Me.adGroupsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property adWordsType() As AdWordsType
            Get
                Return Me.adWordsTypeField
            End Get
            Set(ByVal value As AdWordsType)
                Me.adWordsTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property adWordsTypeSpecified() As Boolean
            Get
                Return Me.adWordsTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.adWordsTypeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("campaignStatuses")> _
        Public Property campaignStatuses() As CampaignStatus()
            Get
                Return Me.campaignStatusesField
            End Get
            Set(ByVal value As CampaignStatus())
                Me.campaignStatusesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("campaigns")> _
        Public Property campaigns() As Integer()
            Get
                Return Me.campaignsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("customOptions")> _
        Public Property customOptions() As CustomReportOption()
            Get
                Return Me.customOptionsField
            End Get
            Set(ByVal value As CustomReportOption())
                Me.customOptionsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property includeZeroImpression() As Boolean
            Get
                Return Me.includeZeroImpressionField
            End Get
            Set(ByVal value As Boolean)
                Me.includeZeroImpressionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property includeZeroImpressionSpecified() As Boolean
            Get
                Return Me.includeZeroImpressionFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.includeZeroImpressionFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("keywordStatuses")> _
        Public Property keywordStatuses() As KeywordStatus()
            Get
                Return Me.keywordStatusesField
            End Get
            Set(ByVal value As KeywordStatus())
                Me.keywordStatusesField = value
            End Set
        End Property

        '''<remarks/>
        Public Property keywordType() As KeywordType
            Get
                Return Me.keywordTypeField
            End Get
            Set(ByVal value As KeywordType)
                Me.keywordTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property keywordTypeSpecified() As Boolean
            Get
                Return Me.keywordTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.keywordTypeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("keywords")> _
        Public Property keywords() As String()
            Get
                Return Me.keywordsField
            End Get
            Set(ByVal value As String())
                Me.keywordsField = value
            End Set
        End Property

        Public Sub New()

        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Public Enum AdGroupStatus

        '''<remarks/>
        Enabled

        '''<remarks/>
        Paused

        '''<remarks/>
        Deleted
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Public Enum CampaignStatus

        '''<remarks/>
        Active

        '''<remarks/>
        Pending

        '''<remarks/>
        Ended

        '''<remarks/>
        Paused

        '''<remarks/>
        Deleted

        '''<remarks/>
        Suspended
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Public Enum CustomReportOption

        '''<remarks/>
        Clicks

        '''<remarks/>
        Impressions

        '''<remarks/>
        Ctr

        '''<remarks/>
        Cpc

        '''<remarks/>
        Cost

        '''<remarks/>
        MinimumCpc

        '''<remarks/>
        MaximumCpc

        '''<remarks/>
        DailyBudget

        '''<remarks/>
        AveragePosition

        '''<remarks/>
        DescriptionLine1

        '''<remarks/>
        DescriptionLine2

        '''<remarks/>
        DescriptionLine3

        '''<remarks/>
        VisibleUrl

        '''<remarks/>
        CreativeDestinationUrl

        '''<remarks/>
        KeywordDestinationUrl

        '''<remarks/>
        DestinationUrl

        '''<remarks/>
        CreativeStatus

        '''<remarks/>
        AdGroupStatus

        '''<remarks/>
        Conversions

        '''<remarks/>
        ConversionRate

        '''<remarks/>
        CostPerConversion

        '''<remarks/>
        Transactions

        '''<remarks/>
        CostPerTransaction

        '''<remarks/>
        TotalConversionValue

        '''<remarks/>
        AverageConversionValue

        '''<remarks/>
        ConversionValuePerCost

        '''<remarks/>
        ConversionValuePerClick

        '''<remarks/>
        SaleCount

        '''<remarks/>
        SaleValue

        '''<remarks/>
        LeadCount

        '''<remarks/>
        LeadValue

        '''<remarks/>
        SignupCount

        '''<remarks/>
        SignupValue

        '''<remarks/>
        PageViewCount

        '''<remarks/>
        PageViewValue

        '''<remarks/>
        DefaultConversionCount

        '''<remarks/>
        DefaultConversionValue

        '''<remarks/>
        Campaign

        '''<remarks/>
        AdGroup

        '''<remarks/>
        Keyword

        '''<remarks/>
        KeywordType

        '''<remarks/>
        KeywordStatus

        '''<remarks/>
        AdWordsType

        '''<remarks/>
        AccountName

        '''<remarks/>
        CampaignStatus

        '''<remarks/>
        CampaignEndDate

        '''<remarks/>
        CampaignId

        '''<remarks/>
        AdGroupId

        '''<remarks/>
        KeywordId

        '''<remarks/>
        CreativeId

        '''<remarks/>
        ImageAdName

        '''<remarks/>
        ImageHostingKey

        '''<remarks/>
        CreativeType

        '''<remarks/>
        BottomPosition

        '''<remarks/>
        TopPosition

        '''<remarks/>
        CPM

        '''<remarks/>
        CustomerTimeZone

        '''<remarks/>
        MaxContentCPC

        '''<remarks/>
        MaximumCPM

        '''<remarks/>
        Website

        '''<remarks/>
        CurrencyCode

        '''<remarks/>
        CustomerId

        '''<remarks/>
        PhoneNumber

        '''<remarks/>
        BusinessName

        '''<remarks/>
        BusinessAddress
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public Class CampaignReportJob
        Inherits ReportJob

        Private adWordsTypeField As AdWordsType

        Private adWordsTypeFieldSpecified As Boolean

        Private campaignsField() As Integer

        '''<remarks/>
        Public Property adWordsType() As AdWordsType
            Get
                Return Me.adWordsTypeField
            End Get
            Set(ByVal value As AdWordsType)
                Me.adWordsTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property adWordsTypeSpecified() As Boolean
            Get
                Return Me.adWordsTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.adWordsTypeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("campaigns")> _
        Public Property campaigns() As Integer()
            Get
                Return Me.campaignsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public Class AdTextReportJob
        Inherits ReportJob

        Private adWordsTypeField As AdWordsType

        Private adWordsTypeFieldSpecified As Boolean

        Private campaignsField() As Integer

        '''<remarks/>
        Public Property adWordsType() As AdWordsType
            Get
                Return Me.adWordsTypeField
            End Get
            Set(ByVal value As AdWordsType)
                Me.adWordsTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property adWordsTypeSpecified() As Boolean
            Get
                Return Me.adWordsTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.adWordsTypeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("campaigns")> _
        Public Property campaigns() As Integer()
            Get
                Return Me.campaignsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public Class AdImageReportJob
        Inherits ReportJob

        Private campaignsField() As Integer

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("campaigns")> _
        Public Property campaigns() As Integer()
            Get
                Return Me.campaignsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public Class AdGroupReportJob
        Inherits ReportJob

        Private adGroupStatusesField() As AdGroupStatus

        Private adWordsTypeField As AdWordsType

        Private adWordsTypeFieldSpecified As Boolean

        Private campaignsField() As Integer

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("adGroupStatuses")> _
        Public Property adGroupStatuses() As AdGroupStatus()
            Get
                Return Me.adGroupStatusesField
            End Get
            Set(ByVal value As AdGroupStatus())
                Me.adGroupStatusesField = value
            End Set
        End Property

        '''<remarks/>
        Public Property adWordsType() As AdWordsType
            Get
                Return Me.adWordsTypeField
            End Get
            Set(ByVal value As AdWordsType)
                Me.adWordsTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property adWordsTypeSpecified() As Boolean
            Get
                Return Me.adWordsTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.adWordsTypeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("campaigns")> _
        Public Property campaigns() As Integer()
            Get
                Return Me.campaignsField
            End Get
            Set(ByVal value As Integer())
                Me.campaignsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://adwords.google.com/api/adwords/v10")> _
    Partial Public Class AccountReportJob
        Inherits ReportJob

        Private adWordsTypeField As AdWordsType

        Private adWordsTypeFieldSpecified As Boolean

        '''<remarks/>
        Public Property adWordsType() As AdWordsType
            Get
                Return Me.adWordsTypeField
            End Get
            Set(ByVal value As AdWordsType)
                Me.adWordsTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property adWordsTypeSpecified() As Boolean
            Get
                Return Me.adWordsTypeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.adWordsTypeFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub deleteReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getAllJobsCompletedEventHandler(ByVal sender As Object, ByVal e As getAllJobsCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getAllJobsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As ReportJob()
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), ReportJob())
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getGzipReportDownloadUrlCompletedEventHandler(ByVal sender As Object, ByVal e As getGzipReportDownloadUrlCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getGzipReportDownloadUrlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getReportDownloadUrlCompletedEventHandler(ByVal sender As Object, ByVal e As getReportDownloadUrlCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getReportDownloadUrlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getReportJobStatusCompletedEventHandler(ByVal sender As Object, ByVal e As getReportJobStatusCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getReportJobStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As ReportJobStatus
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), ReportJobStatus)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub scheduleReportJobCompletedEventHandler(ByVal sender As Object, ByVal e As scheduleReportJobCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class scheduleReportJobCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), Long)
            End Get
        End Property
    End Class
End Namespace