'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

Namespace VerizonWebServices
    '
    'This source code was auto-generated by wsdl, Version=2.0.50727.42.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="spBinding", [Namespace]:="https://my.superpages.com/api"), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ServiceResponse)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ServiceRequest))> _
    Partial Public Class spService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private usernameValueField As username

        Private passwordValueField As password

        Private companyIdValueField As companyId

        Private scheduleReportOperationCompleted As System.Threading.SendOrPostCallback

        Private getDailySummaryReportOperationCompleted As System.Threading.SendOrPostCallback

        Private getReportOperationCompleted As System.Threading.SendOrPostCallback

        Private getReportURLOperationCompleted As System.Threading.SendOrPostCallback

        Private getDailyReportOperationCompleted As System.Threading.SendOrPostCallback

        Private getReportListOperationCompleted As System.Threading.SendOrPostCallback

        Private deleteReportOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = "https://services.superpages.com/webspub/spapi/v1/reporting.jws"
        End Sub

        Public Property usernameValue() As username
            Get
                Return Me.usernameValueField
            End Get
            Set(ByVal value As username)
                Me.usernameValueField = Value
            End Set
        End Property

        Public Property passwordValue() As password
            Get
                Return Me.passwordValueField
            End Get
            Set(ByVal value As password)
                Me.passwordValueField = Value
            End Set
        End Property

        Public Property companyIdValue() As companyId
            Get
                Return Me.companyIdValueField
            End Get
            Set(ByVal value As companyId)
                Me.companyIdValueField = Value
            End Set
        End Property

        '''<remarks/>
        Public Event scheduleReportCompleted As scheduleReportCompletedEventHandler

        '''<remarks/>
        Public Event getDailySummaryReportCompleted As getDailySummaryReportCompletedEventHandler

        '''<remarks/>
        Public Event getReportCompleted As getReportCompletedEventHandler

        '''<remarks/>
        Public Event getReportURLCompleted As getReportURLCompletedEventHandler

        '''<remarks/>
        Public Event getDailyReportCompleted As getDailyReportCompletedEventHandler

        '''<remarks/>
        Public Event getReportListCompleted As getReportListCompletedEventHandler

        '''<remarks/>
        Public Event deleteReportCompleted As deleteReportCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("usernameValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//my.superpages.com/api/scheduleReport", RequestNamespace:="https://my.superpages.com/api", ResponseNamespace:="https://my.superpages.com/api", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function scheduleReport(ByVal parameters As ScheduleReportRequest) As ScheduleReportResponse
            Dim results() As Object = Me.Invoke("scheduleReport", New Object() {parameters})
            Return CType(results(0), ScheduleReportResponse)
        End Function

        '''<remarks/>
        Public Function BeginscheduleReport(ByVal parameters As ScheduleReportRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("scheduleReport", New Object() {parameters}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndscheduleReport(ByVal asyncResult As System.IAsyncResult) As ScheduleReportResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), ScheduleReportResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub scheduleReportAsync(ByVal parameters As ScheduleReportRequest)
            Me.scheduleReportAsync(parameters, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub scheduleReportAsync(ByVal parameters As ScheduleReportRequest, ByVal userState As Object)
            If (Me.scheduleReportOperationCompleted Is Nothing) Then
                Me.scheduleReportOperationCompleted = AddressOf Me.OnscheduleReportOperationCompleted
            End If
            Me.InvokeAsync("scheduleReport", New Object() {parameters}, Me.scheduleReportOperationCompleted, userState)
        End Sub

        Private Sub OnscheduleReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.scheduleReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent scheduleReportCompleted(Me, New scheduleReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("usernameValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//my.superpages.com/api/getDailySummaryReport", RequestNamespace:="https://my.superpages.com/api", ResponseNamespace:="https://my.superpages.com/api", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getDailySummaryReport(ByVal parameters As GetDailySummaryReportRequest) As GetDailySummaryReportResponse
            Dim results() As Object = Me.Invoke("getDailySummaryReport", New Object() {parameters})
            Return CType(results(0), GetDailySummaryReportResponse)
        End Function

        '''<remarks/>
        Public Function BegingetDailySummaryReport(ByVal parameters As GetDailySummaryReportRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getDailySummaryReport", New Object() {parameters}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetDailySummaryReport(ByVal asyncResult As System.IAsyncResult) As GetDailySummaryReportResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), GetDailySummaryReportResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub getDailySummaryReportAsync(ByVal parameters As GetDailySummaryReportRequest)
            Me.getDailySummaryReportAsync(parameters, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getDailySummaryReportAsync(ByVal parameters As GetDailySummaryReportRequest, ByVal userState As Object)
            If (Me.getDailySummaryReportOperationCompleted Is Nothing) Then
                Me.getDailySummaryReportOperationCompleted = AddressOf Me.OngetDailySummaryReportOperationCompleted
            End If
            Me.InvokeAsync("getDailySummaryReport", New Object() {parameters}, Me.getDailySummaryReportOperationCompleted, userState)
        End Sub

        Private Sub OngetDailySummaryReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDailySummaryReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDailySummaryReportCompleted(Me, New getDailySummaryReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("usernameValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//my.superpages.com/api/getReport", RequestNamespace:="https://my.superpages.com/api", ResponseNamespace:="https://my.superpages.com/api", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getReport(ByVal parameters As GetReportRequest) As GetReportResponse
            Dim results() As Object = Me.Invoke("getReport", New Object() {parameters})
            Return CType(results(0), GetReportResponse)
        End Function

        '''<remarks/>
        Public Function BegingetReport(ByVal parameters As GetReportRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getReport", New Object() {parameters}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetReport(ByVal asyncResult As System.IAsyncResult) As GetReportResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), GetReportResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub getReportAsync(ByVal parameters As GetReportRequest)
            Me.getReportAsync(parameters, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getReportAsync(ByVal parameters As GetReportRequest, ByVal userState As Object)
            If (Me.getReportOperationCompleted Is Nothing) Then
                Me.getReportOperationCompleted = AddressOf Me.OngetReportOperationCompleted
            End If
            Me.InvokeAsync("getReport", New Object() {parameters}, Me.getReportOperationCompleted, userState)
        End Sub

        Private Sub OngetReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.getReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getReportCompleted(Me, New getReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("usernameValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//my.superpages.com/api/getReportURL", RequestNamespace:="https://my.superpages.com/api", ResponseNamespace:="https://my.superpages.com/api", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getReportURL(ByVal parameters As GetReportURLRequest) As GetReportURLResponse
            Dim results() As Object = Me.Invoke("getReportURL", New Object() {parameters})
            Return CType(results(0), GetReportURLResponse)
        End Function

        '''<remarks/>
        Public Function BegingetReportURL(ByVal parameters As GetReportURLRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getReportURL", New Object() {parameters}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetReportURL(ByVal asyncResult As System.IAsyncResult) As GetReportURLResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), GetReportURLResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub getReportURLAsync(ByVal parameters As GetReportURLRequest)
            Me.getReportURLAsync(parameters, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getReportURLAsync(ByVal parameters As GetReportURLRequest, ByVal userState As Object)
            If (Me.getReportURLOperationCompleted Is Nothing) Then
                Me.getReportURLOperationCompleted = AddressOf Me.OngetReportURLOperationCompleted
            End If
            Me.InvokeAsync("getReportURL", New Object() {parameters}, Me.getReportURLOperationCompleted, userState)
        End Sub

        Private Sub OngetReportURLOperationCompleted(ByVal arg As Object)
            If (Not (Me.getReportURLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getReportURLCompleted(Me, New getReportURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("usernameValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//my.superpages.com/api/getDailyReport", RequestNamespace:="https://my.superpages.com/api", ResponseNamespace:="https://my.superpages.com/api", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getDailyReport(ByVal parameters As GetDailyReportRequest) As GetDailyReportResponse
            Dim results() As Object = Me.Invoke("getDailyReport", New Object() {parameters})
            Return CType(results(0), GetDailyReportResponse)
        End Function

        '''<remarks/>
        Public Function BegingetDailyReport(ByVal parameters As GetDailyReportRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getDailyReport", New Object() {parameters}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetDailyReport(ByVal asyncResult As System.IAsyncResult) As GetDailyReportResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), GetDailyReportResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub getDailyReportAsync(ByVal parameters As GetDailyReportRequest)
            Me.getDailyReportAsync(parameters, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getDailyReportAsync(ByVal parameters As GetDailyReportRequest, ByVal userState As Object)
            If (Me.getDailyReportOperationCompleted Is Nothing) Then
                Me.getDailyReportOperationCompleted = AddressOf Me.OngetDailyReportOperationCompleted
            End If
            Me.InvokeAsync("getDailyReport", New Object() {parameters}, Me.getDailyReportOperationCompleted, userState)
        End Sub

        Private Sub OngetDailyReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDailyReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDailyReportCompleted(Me, New getDailyReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("usernameValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//my.superpages.com/api/getReportList", RequestNamespace:="https://my.superpages.com/api", ResponseNamespace:="https://my.superpages.com/api", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getReportList(ByVal parameters As GetReportListRequest) As GetReportListResponse
            Dim results() As Object = Me.Invoke("getReportList", New Object() {parameters})
            Return CType(results(0), GetReportListResponse)
        End Function

        '''<remarks/>
        Public Function BegingetReportList(ByVal parameters As GetReportListRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getReportList", New Object() {parameters}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetReportList(ByVal asyncResult As System.IAsyncResult) As GetReportListResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), GetReportListResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub getReportListAsync(ByVal parameters As GetReportListRequest)
            Me.getReportListAsync(parameters, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getReportListAsync(ByVal parameters As GetReportListRequest, ByVal userState As Object)
            If (Me.getReportListOperationCompleted Is Nothing) Then
                Me.getReportListOperationCompleted = AddressOf Me.OngetReportListOperationCompleted
            End If
            Me.InvokeAsync("getReportList", New Object() {parameters}, Me.getReportListOperationCompleted, userState)
        End Sub

        Private Sub OngetReportListOperationCompleted(ByVal arg As Object)
            If (Not (Me.getReportListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getReportListCompleted(Me, New getReportListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyIdValue"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("usernameValue"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//my.superpages.com/api/deleteReport", RequestNamespace:="https://my.superpages.com/api", ResponseNamespace:="https://my.superpages.com/api", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function deleteReport(ByVal parameters As DeleteReportRequest) As DeleteReportResponse
            Dim results() As Object = Me.Invoke("deleteReport", New Object() {parameters})
            Return CType(results(0), DeleteReportResponse)
        End Function

        '''<remarks/>
        Public Function BegindeleteReport(ByVal parameters As DeleteReportRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("deleteReport", New Object() {parameters}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EnddeleteReport(ByVal asyncResult As System.IAsyncResult) As DeleteReportResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), DeleteReportResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub deleteReportAsync(ByVal parameters As DeleteReportRequest)
            Me.deleteReportAsync(parameters, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub deleteReportAsync(ByVal parameters As DeleteReportRequest, ByVal userState As Object)
            If (Me.deleteReportOperationCompleted Is Nothing) Then
                Me.deleteReportOperationCompleted = AddressOf Me.OndeleteReportOperationCompleted
            End If
            Me.InvokeAsync("deleteReport", New Object() {parameters}, Me.deleteReportOperationCompleted, userState)
        End Sub

        Private Sub OndeleteReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.deleteReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent deleteReportCompleted(Me, New deleteReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://my.superpages.com/api", IsNullable:=False)> _
    Partial Public Class password
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://my.superpages.com/api", IsNullable:=False)> _
    Partial Public Class companyId
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://my.superpages.com/api", IsNullable:=False)> _
    Partial Public Class username
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class ScheduleReportRequest
        Inherits ServiceRequest

        Private reportTypeField As String

        Private startDateField As String

        Private endDateField As String

        '''<remarks/>
        Public Property reportType() As String
            Get
                Return Me.reportTypeField
            End Get
            Set(ByVal value As String)
                Me.reportTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property startDate() As String
            Get
                Return Me.startDateField
            End Get
            Set(ByVal value As String)
                Me.startDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property endDate() As String
            Get
                Return Me.endDateField
            End Get
            Set(ByVal value As String)
                Me.endDateField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(DeleteReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetReportListRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetDailyReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetReportURLRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetDailySummaryReportRequest)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ScheduleReportRequest)), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class ServiceRequest

        Private companyIdField As String

        Private usernameField As String

        Private passwordField As String

        '''<remarks/>
        Public Property companyId() As String
            Get
                Return Me.companyIdField
            End Get
            Set(ByVal value As String)
                Me.companyIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set(ByVal value As String)
                Me.usernameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set(ByVal value As String)
                Me.passwordField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class RankingPerBid

        Private top2BidAmountField As Single

        Private top2BidAmountFieldSpecified As Boolean

        Private top3BidAmountField As Single

        Private top3BidAmountFieldSpecified As Boolean

        Private top4BidAmountField As Single

        Private top4BidAmountFieldSpecified As Boolean

        Private top5BidAmountField As Single

        Private top5BidAmountFieldSpecified As Boolean

        Private top6BidAmountField As Single

        Private top6BidAmountFieldSpecified As Boolean

        Private top7BidAmountField As Single

        Private top7BidAmountFieldSpecified As Boolean

        Private top8BidAmountField As Single

        Private top8BidAmountFieldSpecified As Boolean

        Private top9BidAmountField As Single

        Private top9BidAmountFieldSpecified As Boolean

        Private top10BidAmountField As Single

        Private top10BidAmountFieldSpecified As Boolean

        '''<remarks/>
        Public Property top2BidAmount() As Single
            Get
                Return Me.top2BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top2BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top2BidAmountSpecified() As Boolean
            Get
                Return Me.top2BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top2BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top3BidAmount() As Single
            Get
                Return Me.top3BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top3BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top3BidAmountSpecified() As Boolean
            Get
                Return Me.top3BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top3BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top4BidAmount() As Single
            Get
                Return Me.top4BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top4BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top4BidAmountSpecified() As Boolean
            Get
                Return Me.top4BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top4BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top5BidAmount() As Single
            Get
                Return Me.top5BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top5BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top5BidAmountSpecified() As Boolean
            Get
                Return Me.top5BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top5BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top6BidAmount() As Single
            Get
                Return Me.top6BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top6BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top6BidAmountSpecified() As Boolean
            Get
                Return Me.top6BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top6BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top7BidAmount() As Single
            Get
                Return Me.top7BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top7BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top7BidAmountSpecified() As Boolean
            Get
                Return Me.top7BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top7BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top8BidAmount() As Single
            Get
                Return Me.top8BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top8BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top8BidAmountSpecified() As Boolean
            Get
                Return Me.top8BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top8BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top9BidAmount() As Single
            Get
                Return Me.top9BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top9BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top9BidAmountSpecified() As Boolean
            Get
                Return Me.top9BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top9BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top10BidAmount() As Single
            Get
                Return Me.top10BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top10BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top10BidAmountSpecified() As Boolean
            Get
                Return Me.top10BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top10BidAmountFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class DailyReport

        Private rowCountField As String

        Private reportTypeField As String

        Private dateField As String

        Private customerNameField As String

        Private campaignDestURLAddrField As String

        Private campaingIdField As String

        Private categoryNameField As String

        Private geographyNameField As String

        Private geographyTypeField As String

        Private campaignStatusField As String

        Private budgetAmountField As Single

        Private budgetAmountFieldSpecified As Boolean

        Private monthToDatePFPSpendAmountField As Single

        Private monthToDatePFPSpendAmountFieldSpecified As Boolean

        Private dailyImpressionCountField As Single

        Private dailyImpressionCountFieldSpecified As Boolean

        Private dailyRawClickCountField As Single

        Private dailyRawClickCountFieldSpecified As Boolean

        Private dailyPFPClickCountField As Single

        Private dailyPFPClickCountFieldSpecified As Boolean

        Private averagePositionField As Single

        Private averagePositionFieldSpecified As Boolean

        Private spendPercentField As Single

        Private spendPercentFieldSpecified As Boolean

        Private counterPercentField As Single

        Private counterPercentFieldSpecified As Boolean

        Private bidAmountField As Single

        Private bidAmountFieldSpecified As Boolean

        Private maxBidAmountField As Single

        Private maxBidAmountFieldSpecified As Boolean

        Private rankingPerBidField As RankingPerBid

        '''<remarks/>
        Public Property rowCount() As String
            Get
                Return Me.rowCountField
            End Get
            Set(ByVal value As String)
                Me.rowCountField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property reportType() As String
            Get
                Return Me.reportTypeField
            End Get
            Set(ByVal value As String)
                Me.reportTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set(ByVal value As String)
                Me.dateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property customerName() As String
            Get
                Return Me.customerNameField
            End Get
            Set(ByVal value As String)
                Me.customerNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property campaignDestURLAddr() As String
            Get
                Return Me.campaignDestURLAddrField
            End Get
            Set(ByVal value As String)
                Me.campaignDestURLAddrField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property campaingId() As String
            Get
                Return Me.campaingIdField
            End Get
            Set(ByVal value As String)
                Me.campaingIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property categoryName() As String
            Get
                Return Me.categoryNameField
            End Get
            Set(ByVal value As String)
                Me.categoryNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property geographyName() As String
            Get
                Return Me.geographyNameField
            End Get
            Set(ByVal value As String)
                Me.geographyNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property geographyType() As String
            Get
                Return Me.geographyTypeField
            End Get
            Set(ByVal value As String)
                Me.geographyTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property campaignStatus() As String
            Get
                Return Me.campaignStatusField
            End Get
            Set(ByVal value As String)
                Me.campaignStatusField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property budgetAmount() As Single
            Get
                Return Me.budgetAmountField
            End Get
            Set(ByVal value As Single)
                Me.budgetAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property budgetAmountSpecified() As Boolean
            Get
                Return Me.budgetAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.budgetAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property monthToDatePFPSpendAmount() As Single
            Get
                Return Me.monthToDatePFPSpendAmountField
            End Get
            Set(ByVal value As Single)
                Me.monthToDatePFPSpendAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property monthToDatePFPSpendAmountSpecified() As Boolean
            Get
                Return Me.monthToDatePFPSpendAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.monthToDatePFPSpendAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property dailyImpressionCount() As Single
            Get
                Return Me.dailyImpressionCountField
            End Get
            Set(ByVal value As Single)
                Me.dailyImpressionCountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dailyImpressionCountSpecified() As Boolean
            Get
                Return Me.dailyImpressionCountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dailyImpressionCountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property dailyRawClickCount() As Single
            Get
                Return Me.dailyRawClickCountField
            End Get
            Set(ByVal value As Single)
                Me.dailyRawClickCountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dailyRawClickCountSpecified() As Boolean
            Get
                Return Me.dailyRawClickCountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dailyRawClickCountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property dailyPFPClickCount() As Single
            Get
                Return Me.dailyPFPClickCountField
            End Get
            Set(ByVal value As Single)
                Me.dailyPFPClickCountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dailyPFPClickCountSpecified() As Boolean
            Get
                Return Me.dailyPFPClickCountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dailyPFPClickCountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property averagePosition() As Single
            Get
                Return Me.averagePositionField
            End Get
            Set(ByVal value As Single)
                Me.averagePositionField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property averagePositionSpecified() As Boolean
            Get
                Return Me.averagePositionFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.averagePositionFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property spendPercent() As Single
            Get
                Return Me.spendPercentField
            End Get
            Set(ByVal value As Single)
                Me.spendPercentField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property spendPercentSpecified() As Boolean
            Get
                Return Me.spendPercentFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.spendPercentFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property counterPercent() As Single
            Get
                Return Me.counterPercentField
            End Get
            Set(ByVal value As Single)
                Me.counterPercentField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property counterPercentSpecified() As Boolean
            Get
                Return Me.counterPercentFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.counterPercentFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property bidAmount() As Single
            Get
                Return Me.bidAmountField
            End Get
            Set(ByVal value As Single)
                Me.bidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property bidAmountSpecified() As Boolean
            Get
                Return Me.bidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.bidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property maxBidAmount() As Single
            Get
                Return Me.maxBidAmountField
            End Get
            Set(ByVal value As Single)
                Me.maxBidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property maxBidAmountSpecified() As Boolean
            Get
                Return Me.maxBidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.maxBidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RankingPerBid() As RankingPerBid
            Get
                Return Me.rankingPerBidField
            End Get
            Set(ByVal value As RankingPerBid)
                Me.rankingPerBidField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetDailyReportResponse

        Private dailyReportField() As DailyReport

        '''<remarks/>
        Public Property DailyReport() As DailyReport()
            Get
                Return Me.dailyReportField
            End Get
            Set(ByVal value As DailyReport())
                Me.dailyReportField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetReportURLResponse

        Private uRLField As String

        '''<remarks/>
        Public Property URL() As String
            Get
                Return Me.uRLField
            End Get
            Set(ByVal value As String)
                Me.uRLField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetReportResponse

        Private reportTypeField As String

        Private reportField()() As String

        '''<remarks/>
        Public Property reportType() As String
            Get
                Return Me.reportTypeField
            End Get
            Set(ByVal value As String)
                Me.reportTypeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable:=False), _
         System.Xml.Serialization.XmlArrayItemAttribute("column", IsNullable:=False, NestingLevel:=1)> _
        Public Property report() As String()()
            Get
                Return Me.reportField
            End Get
            Set(ByVal value As String()())
                Me.reportField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(DeleteReportResponse)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetReportListResponse)), _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GetDailySummaryReportResponse)), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class ServiceResponse
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class DeleteReportResponse
        Inherits ServiceResponse

        Private successCodeField As String

        '''<remarks/>
        Public Property successCode() As String
            Get
                Return Me.successCodeField
            End Get
            Set(ByVal value As String)
                Me.successCodeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetReportListResponse
        Inherits ServiceResponse

        Private reportField()() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable:=False), _
         System.Xml.Serialization.XmlArrayItemAttribute("column", IsNullable:=False, NestingLevel:=1)> _
        Public Property report() As String()()
            Get
                Return Me.reportField
            End Get
            Set(ByVal value As String()())
                Me.reportField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetDailySummaryReportResponse
        Inherits ServiceResponse

        Private rowCountField As String

        Private reportTypeField As String

        Private dateField As String

        Private customerNameField As String

        Private campaignsField As String

        Private categoriesField As String

        Private catkeyFlagField As String

        Private geographiesField As String

        Private statusField As String

        Private budgetField As String

        Private monthToDateSpendField As String

        Private monthToDateBillableClicksField As String

        Private maxCpcField As String

        Private impressionsField As String

        Private clicksField As String

        Private spendField As String

        Private averagePositionField As String

        Private spendPercentField As String

        Private billableClicksField As String

        Private ctrField As String

        '''<remarks/>
        Public Property rowCount() As String
            Get
                Return Me.rowCountField
            End Get
            Set(ByVal value As String)
                Me.rowCountField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property reportType() As String
            Get
                Return Me.reportTypeField
            End Get
            Set(ByVal value As String)
                Me.reportTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set(ByVal value As String)
                Me.dateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property customerName() As String
            Get
                Return Me.customerNameField
            End Get
            Set(ByVal value As String)
                Me.customerNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property campaigns() As String
            Get
                Return Me.campaignsField
            End Get
            Set(ByVal value As String)
                Me.campaignsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property categories() As String
            Get
                Return Me.categoriesField
            End Get
            Set(ByVal value As String)
                Me.categoriesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property catkeyFlag() As String
            Get
                Return Me.catkeyFlagField
            End Get
            Set(ByVal value As String)
                Me.catkeyFlagField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property geographies() As String
            Get
                Return Me.geographiesField
            End Get
            Set(ByVal value As String)
                Me.geographiesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set(ByVal value As String)
                Me.statusField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property budget() As String
            Get
                Return Me.budgetField
            End Get
            Set(ByVal value As String)
                Me.budgetField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property monthToDateSpend() As String
            Get
                Return Me.monthToDateSpendField
            End Get
            Set(ByVal value As String)
                Me.monthToDateSpendField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property monthToDateBillableClicks() As String
            Get
                Return Me.monthToDateBillableClicksField
            End Get
            Set(ByVal value As String)
                Me.monthToDateBillableClicksField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property maxCpc() As String
            Get
                Return Me.maxCpcField
            End Get
            Set(ByVal value As String)
                Me.maxCpcField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property impressions() As String
            Get
                Return Me.impressionsField
            End Get
            Set(ByVal value As String)
                Me.impressionsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property clicks() As String
            Get
                Return Me.clicksField
            End Get
            Set(ByVal value As String)
                Me.clicksField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property spend() As String
            Get
                Return Me.spendField
            End Get
            Set(ByVal value As String)
                Me.spendField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property averagePosition() As String
            Get
                Return Me.averagePositionField
            End Get
            Set(ByVal value As String)
                Me.averagePositionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property spendPercent() As String
            Get
                Return Me.spendPercentField
            End Get
            Set(ByVal value As String)
                Me.spendPercentField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property billableClicks() As String
            Get
                Return Me.billableClicksField
            End Get
            Set(ByVal value As String)
                Me.billableClicksField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ctr() As String
            Get
                Return Me.ctrField
            End Get
            Set(ByVal value As String)
                Me.ctrField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class ScheduleReportResponse

        Private reportIdField As String

        '''<remarks/>
        Public Property reportId() As String
            Get
                Return Me.reportIdField
            End Get
            Set(ByVal value As String)
                Me.reportIdField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class DeleteReportRequest
        Inherits ServiceRequest

        Private reportIdField As String

        '''<remarks/>
        Public Property reportId() As String
            Get
                Return Me.reportIdField
            End Get
            Set(ByVal value As String)
                Me.reportIdField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetReportListRequest
        Inherits ServiceRequest
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetDailyReportRequest
        Inherits ServiceRequest

        Private dateField As String

        '''<remarks/>
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set(ByVal value As String)
                Me.dateField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetReportURLRequest
        Inherits ServiceRequest

        Private reportIdField As String

        '''<remarks/>
        Public Property reportId() As String
            Get
                Return Me.reportIdField
            End Get
            Set(ByVal value As String)
                Me.reportIdField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetReportRequest
        Inherits ServiceRequest

        Private reportIdField As String

        '''<remarks/>
        Public Property reportId() As String
            Get
                Return Me.reportIdField
            End Get
            Set(ByVal value As String)
                Me.reportIdField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://my.superpages.com/api")> _
    Partial Public Class GetDailySummaryReportRequest
        Inherits ServiceRequest

        Private dateField As String

        '''<remarks/>
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set(ByVal value As String)
                Me.dateField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub scheduleReportCompletedEventHandler(ByVal sender As Object, ByVal e As scheduleReportCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class scheduleReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As ScheduleReportResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), ScheduleReportResponse)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getDailySummaryReportCompletedEventHandler(ByVal sender As Object, ByVal e As getDailySummaryReportCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getDailySummaryReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As GetDailySummaryReportResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), GetDailySummaryReportResponse)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getReportCompletedEventHandler(ByVal sender As Object, ByVal e As getReportCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As GetReportResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), GetReportResponse)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getReportURLCompletedEventHandler(ByVal sender As Object, ByVal e As getReportURLCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getReportURLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As GetReportURLResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), GetReportURLResponse)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getDailyReportCompletedEventHandler(ByVal sender As Object, ByVal e As getDailyReportCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getDailyReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As GetDailyReportResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), GetDailyReportResponse)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getReportListCompletedEventHandler(ByVal sender As Object, ByVal e As getReportListCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getReportListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As GetReportListResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), GetReportListResponse)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub deleteReportCompletedEventHandler(ByVal sender As Object, ByVal e As deleteReportCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class deleteReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As DeleteReportResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), DeleteReportResponse)
            End Get
        End Property
    End Class

End Namespace
