'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

Namespace VerizonWebServices
    '
    'This source code was auto-generated by wsdl, Version=2.0.50727.42.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="ReportingServiceHttpBinding", [Namespace]:="https://services.superpages.com/spapi/v2")> _
    Partial Public Class ReportingService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private passwordField As [string]

        Private companyIdField As string1

        Private usernameField As string2

        Private scheduleReportOperationCompleted As System.Threading.SendOrPostCallback

        Private getReportURLOperationCompleted As System.Threading.SendOrPostCallback

        Private deleteReportOperationCompleted As System.Threading.SendOrPostCallback

        Private getDailySummaryReportOperationCompleted As System.Threading.SendOrPostCallback

        Private getReportListOperationCompleted As System.Threading.SendOrPostCallback

        Private getDailyReportOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = "http://services.superpages.com/spapi/services/ReportingService"
        End Sub

        Public Property password() As [string]
            Get
                Return Me.passwordField
            End Get
            Set(ByVal value As [string])
                Me.passwordField = Value
            End Set
        End Property

        Public Property companyId() As string1
            Get
                Return Me.companyIdField
            End Get
            Set(ByVal value As string1)
                Me.companyIdField = Value
            End Set
        End Property

        Public Property username() As string2
            Get
                Return Me.usernameField
            End Get
            Set(ByVal value As string2)
                Me.usernameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Event scheduleReportCompleted As scheduleReportCompletedEventHandler

        '''<remarks/>
        Public Event getReportURLCompleted As getReportURLCompletedEventHandler

        '''<remarks/>
        Public Event deleteReportCompleted As deleteReportCompletedEventHandler

        '''<remarks/>
        Public Event getDailySummaryReportCompleted As getDailySummaryReportCompletedEventHandler

        '''<remarks/>
        Public Event getReportListCompleted As getReportListCompletedEventHandler

        '''<remarks/>
        Public Event getDailyReportCompleted As getDailyReportCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("password"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyId"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("username"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://services.superpages.com/spapi/v2", ResponseNamespace:="https://services.superpages.com/spapi/v2", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function scheduleReport(ByVal reportType As String, ByVal startDate As String, ByVal endDate As String) As String
            Dim results() As Object = Me.Invoke("scheduleReport", New Object() {reportType, startDate, endDate})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Function BeginscheduleReport(ByVal reportType As String, ByVal startDate As String, ByVal endDate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("scheduleReport", New Object() {reportType, startDate, endDate}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndscheduleReport(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub scheduleReportAsync(ByVal reportType As String, ByVal startDate As String, ByVal endDate As String)
            Me.scheduleReportAsync(reportType, startDate, endDate, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub scheduleReportAsync(ByVal reportType As String, ByVal startDate As String, ByVal endDate As String, ByVal userState As Object)
            If (Me.scheduleReportOperationCompleted Is Nothing) Then
                Me.scheduleReportOperationCompleted = AddressOf Me.OnscheduleReportOperationCompleted
            End If
            Me.InvokeAsync("scheduleReport", New Object() {reportType, startDate, endDate}, Me.scheduleReportOperationCompleted, userState)
        End Sub

        Private Sub OnscheduleReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.scheduleReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent scheduleReportCompleted(Me, New scheduleReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("password"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyId"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("username"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://services.superpages.com/spapi/v2", ResponseNamespace:="https://services.superpages.com/spapi/v2", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getReportURL(ByVal reportId As String) As String
            Dim results() As Object = Me.Invoke("getReportURL", New Object() {reportId})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Function BegingetReportURL(ByVal reportId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getReportURL", New Object() {reportId}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetReportURL(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub getReportURLAsync(ByVal reportId As String)
            Me.getReportURLAsync(reportId, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getReportURLAsync(ByVal reportId As String, ByVal userState As Object)
            If (Me.getReportURLOperationCompleted Is Nothing) Then
                Me.getReportURLOperationCompleted = AddressOf Me.OngetReportURLOperationCompleted
            End If
            Me.InvokeAsync("getReportURL", New Object() {reportId}, Me.getReportURLOperationCompleted, userState)
        End Sub

        Private Sub OngetReportURLOperationCompleted(ByVal arg As Object)
            If (Not (Me.getReportURLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getReportURLCompleted(Me, New getReportURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("password"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyId"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("username"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://services.superpages.com/spapi/v2", ResponseNamespace:="https://services.superpages.com/spapi/v2", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Sub deleteReport(ByVal reportId As String)
            Me.Invoke("deleteReport", New Object() {reportId})
        End Sub

        '''<remarks/>
        Public Function BegindeleteReport(ByVal reportId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("deleteReport", New Object() {reportId}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Sub EnddeleteReport(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub

        '''<remarks/>
        Public Overloads Sub deleteReportAsync(ByVal reportId As String)
            Me.deleteReportAsync(reportId, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub deleteReportAsync(ByVal reportId As String, ByVal userState As Object)
            If (Me.deleteReportOperationCompleted Is Nothing) Then
                Me.deleteReportOperationCompleted = AddressOf Me.OndeleteReportOperationCompleted
            End If
            Me.InvokeAsync("deleteReport", New Object() {reportId}, Me.deleteReportOperationCompleted, userState)
        End Sub

        Private Sub OndeleteReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.deleteReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent deleteReportCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("password"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyId"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("username"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://services.superpages.com/spapi/v2", ResponseNamespace:="https://services.superpages.com/spapi/v2", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getDailySummaryReport(ByVal [date] As String) As DailySummaryReport
            Dim results() As Object = Me.Invoke("getDailySummaryReport", New Object() {[date]})
            Return CType(results(0), DailySummaryReport)
        End Function

        '''<remarks/>
        Public Function BegingetDailySummaryReport(ByVal [date] As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getDailySummaryReport", New Object() {[date]}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetDailySummaryReport(ByVal asyncResult As System.IAsyncResult) As DailySummaryReport
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), DailySummaryReport)
        End Function

        '''<remarks/>
        Public Overloads Sub getDailySummaryReportAsync(ByVal [date] As String)
            Me.getDailySummaryReportAsync([date], Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getDailySummaryReportAsync(ByVal [date] As String, ByVal userState As Object)
            If (Me.getDailySummaryReportOperationCompleted Is Nothing) Then
                Me.getDailySummaryReportOperationCompleted = AddressOf Me.OngetDailySummaryReportOperationCompleted
            End If
            Me.InvokeAsync("getDailySummaryReport", New Object() {[date]}, Me.getDailySummaryReportOperationCompleted, userState)
        End Sub

        Private Sub OngetDailySummaryReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDailySummaryReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDailySummaryReportCompleted(Me, New getDailySummaryReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("password"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyId"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("username"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://services.superpages.com/spapi/v2", ResponseNamespace:="https://services.superpages.com/spapi/v2", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getReportList() As ReportList
            Dim results() As Object = Me.Invoke("getReportList", New Object(-1) {})
            Return CType(results(0), ReportList)
        End Function

        '''<remarks/>
        Public Function BegingetReportList(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getReportList", New Object(-1) {}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetReportList(ByVal asyncResult As System.IAsyncResult) As ReportList
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), ReportList)
        End Function

        '''<remarks/>
        Public Overloads Sub getReportListAsync()
            Me.getReportListAsync(Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getReportListAsync(ByVal userState As Object)
            If (Me.getReportListOperationCompleted Is Nothing) Then
                Me.getReportListOperationCompleted = AddressOf Me.OngetReportListOperationCompleted
            End If
            Me.InvokeAsync("getReportList", New Object(-1) {}, Me.getReportListOperationCompleted, userState)
        End Sub

        Private Sub OngetReportListOperationCompleted(ByVal arg As Object)
            If (Not (Me.getReportListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getReportListCompleted(Me, New getReportListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("password"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("companyId"), _
         System.Web.Services.Protocols.SoapHeaderAttribute("username"), _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="https://services.superpages.com/spapi/v2", ResponseNamespace:="https://services.superpages.com/spapi/v2", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getDailyReport(ByVal [date] As String) As <System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://common.spapi.idearc.com", IsNullable:=False)> DailyReport()
            Dim results() As Object = Me.Invoke("getDailyReport", New Object() {[date]})
            Return CType(results(0), DailyReport())
        End Function

        '''<remarks/>
        Public Function BegingetDailyReport(ByVal [date] As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getDailyReport", New Object() {[date]}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndgetDailyReport(ByVal asyncResult As System.IAsyncResult) As DailyReport()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), DailyReport())
        End Function

        '''<remarks/>
        Public Overloads Sub getDailyReportAsync(ByVal [date] As String)
            Me.getDailyReportAsync([date], Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getDailyReportAsync(ByVal [date] As String, ByVal userState As Object)
            If (Me.getDailyReportOperationCompleted Is Nothing) Then
                Me.getDailyReportOperationCompleted = AddressOf Me.OngetDailyReportOperationCompleted
            End If
            Me.InvokeAsync("getDailyReport", New Object() {[date]}, Me.getDailyReportOperationCompleted, userState)
        End Sub

        Private Sub OngetDailyReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDailyReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDailyReportCompleted(Me, New getDailyReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2001/XMLSchema"), _
     System.Xml.Serialization.XmlRootAttribute("password", [Namespace]:="https://services.superpages.com/spapi/v2", IsNullable:=False)> _
    Partial Public Class [string]
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="string", [Namespace]:="http://www.w3.org/2001/XMLSchema"), _
     System.Xml.Serialization.XmlRootAttribute("companyId", [Namespace]:="https://services.superpages.com/spapi/v2", IsNullable:=False)> _
    Partial Public Class string1
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="string", [Namespace]:="http://www.w3.org/2001/XMLSchema"), _
     System.Xml.Serialization.XmlRootAttribute("username", [Namespace]:="https://services.superpages.com/spapi/v2", IsNullable:=False)> _
    Partial Public Class string2
        Inherits System.Web.Services.Protocols.SoapHeader

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String())
                Me.textField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://common.spapi.idearc.com")> _
    Partial Public Class DailySummaryReport

        Private averagePositionField As String

        Private billableClicksField As String

        Private budgetField As String

        Private campaignsField As String

        Private categoriesField As String

        Private catkeyFlagField As String

        Private clicksField As String

        Private ctrField As String

        Private customerField As String

        Private dateField As String

        Private geographiesField As String

        Private impressionsField As String

        Private maxCpcField As String

        Private monthToDateBillableClicksField As String

        Private monthTODateSpendField As String

        Private spendField As String

        Private spendPercentField As String

        Private statusField As String

        '''<remarks/>
        Public Property averagePosition() As String
            Get
                Return Me.averagePositionField
            End Get
            Set(ByVal value As String)
                Me.averagePositionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property billableClicks() As String
            Get
                Return Me.billableClicksField
            End Get
            Set(ByVal value As String)
                Me.billableClicksField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property budget() As String
            Get
                Return Me.budgetField
            End Get
            Set(ByVal value As String)
                Me.budgetField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property campaigns() As String
            Get
                Return Me.campaignsField
            End Get
            Set(ByVal value As String)
                Me.campaignsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property categories() As String
            Get
                Return Me.categoriesField
            End Get
            Set(ByVal value As String)
                Me.categoriesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property catkeyFlag() As String
            Get
                Return Me.catkeyFlagField
            End Get
            Set(ByVal value As String)
                Me.catkeyFlagField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property clicks() As String
            Get
                Return Me.clicksField
            End Get
            Set(ByVal value As String)
                Me.clicksField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ctr() As String
            Get
                Return Me.ctrField
            End Get
            Set(ByVal value As String)
                Me.ctrField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property customer() As String
            Get
                Return Me.customerField
            End Get
            Set(ByVal value As String)
                Me.customerField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set(ByVal value As String)
                Me.dateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property geographies() As String
            Get
                Return Me.geographiesField
            End Get
            Set(ByVal value As String)
                Me.geographiesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property impressions() As String
            Get
                Return Me.impressionsField
            End Get
            Set(ByVal value As String)
                Me.impressionsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property maxCpc() As String
            Get
                Return Me.maxCpcField
            End Get
            Set(ByVal value As String)
                Me.maxCpcField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property monthToDateBillableClicks() As String
            Get
                Return Me.monthToDateBillableClicksField
            End Get
            Set(ByVal value As String)
                Me.monthToDateBillableClicksField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property monthTODateSpend() As String
            Get
                Return Me.monthTODateSpendField
            End Get
            Set(ByVal value As String)
                Me.monthTODateSpendField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property spend() As String
            Get
                Return Me.spendField
            End Get
            Set(ByVal value As String)
                Me.spendField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property spendPercent() As String
            Get
                Return Me.spendPercentField
            End Get
            Set(ByVal value As String)
                Me.spendPercentField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set(ByVal value As String)
                Me.statusField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://common.spapi.idearc.com")> _
    Partial Public Class RankingPerBid

        Private top10BidAmountField As Single

        Private top10BidAmountFieldSpecified As Boolean

        Private top2BidAmountField As Single

        Private top2BidAmountFieldSpecified As Boolean

        Private top3BidAmountField As Single

        Private top3BidAmountFieldSpecified As Boolean

        Private top4BidAmountField As Single

        Private top4BidAmountFieldSpecified As Boolean

        Private top5BidAmountField As Single

        Private top5BidAmountFieldSpecified As Boolean

        Private top6BidAmountField As Single

        Private top6BidAmountFieldSpecified As Boolean

        Private top7BidAmountField As Single

        Private top7BidAmountFieldSpecified As Boolean

        Private top8BidAmountField As Single

        Private top8BidAmountFieldSpecified As Boolean

        Private top9BidAmountField As Single

        Private top9BidAmountFieldSpecified As Boolean

        '''<remarks/>
        Public Property top10BidAmount() As Single
            Get
                Return Me.top10BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top10BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top10BidAmountSpecified() As Boolean
            Get
                Return Me.top10BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top10BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top2BidAmount() As Single
            Get
                Return Me.top2BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top2BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top2BidAmountSpecified() As Boolean
            Get
                Return Me.top2BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top2BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top3BidAmount() As Single
            Get
                Return Me.top3BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top3BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top3BidAmountSpecified() As Boolean
            Get
                Return Me.top3BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top3BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top4BidAmount() As Single
            Get
                Return Me.top4BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top4BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top4BidAmountSpecified() As Boolean
            Get
                Return Me.top4BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top4BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top5BidAmount() As Single
            Get
                Return Me.top5BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top5BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top5BidAmountSpecified() As Boolean
            Get
                Return Me.top5BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top5BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top6BidAmount() As Single
            Get
                Return Me.top6BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top6BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top6BidAmountSpecified() As Boolean
            Get
                Return Me.top6BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top6BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top7BidAmount() As Single
            Get
                Return Me.top7BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top7BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top7BidAmountSpecified() As Boolean
            Get
                Return Me.top7BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top7BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top8BidAmount() As Single
            Get
                Return Me.top8BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top8BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top8BidAmountSpecified() As Boolean
            Get
                Return Me.top8BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top8BidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property top9BidAmount() As Single
            Get
                Return Me.top9BidAmountField
            End Get
            Set(ByVal value As Single)
                Me.top9BidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property top9BidAmountSpecified() As Boolean
            Get
                Return Me.top9BidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.top9BidAmountFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://common.spapi.idearc.com")> _
    Partial Public Class DailyReport

        Private averagePositionField As Single

        Private averagePositionFieldSpecified As Boolean

        Private bidAmountField As Single

        Private bidAmountFieldSpecified As Boolean

        Private budgetAmountField As Single

        Private budgetAmountFieldSpecified As Boolean

        Private campaignDestURLAddrField As String

        Private campaignStatusField As String

        Private campaignIdField As String

        Private categoryNameField As String

        Private counterPercentField As Single

        Private counterPercentFieldSpecified As Boolean

        Private customerNameField As String

        Private dailyImpressionCountField As Single

        Private dailyImpressionCountFieldSpecified As Boolean

        Private dailyPFPClickCountField As Single

        Private dailyPFPClickCountFieldSpecified As Boolean

        Private dailyRawClickCountField As Single

        Private dailyRawClickCountFieldSpecified As Boolean

        Private dateField As String

        Private geographyNameField As String

        Private geographyTypeField As String

        Private maxBidAmountField As Single

        Private maxBidAmountFieldSpecified As Boolean

        Private monthoDatePFPSpendAmountField As Single

        Private monthoDatePFPSpendAmountFieldSpecified As Boolean

        Private rankperBidField As RankingPerBid

        Private spendPercentField As Single

        Private spendPercentFieldSpecified As Boolean

        '''<remarks/>
        Public Property averagePosition() As Single
            Get
                Return Me.averagePositionField
            End Get
            Set(ByVal value As Single)
                Me.averagePositionField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property averagePositionSpecified() As Boolean
            Get
                Return Me.averagePositionFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.averagePositionFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property bidAmount() As Single
            Get
                Return Me.bidAmountField
            End Get
            Set(ByVal value As Single)
                Me.bidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property bidAmountSpecified() As Boolean
            Get
                Return Me.bidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.bidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property budgetAmount() As Single
            Get
                Return Me.budgetAmountField
            End Get
            Set(ByVal value As Single)
                Me.budgetAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property budgetAmountSpecified() As Boolean
            Get
                Return Me.budgetAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.budgetAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property campaignDestURLAddr() As String
            Get
                Return Me.campaignDestURLAddrField
            End Get
            Set(ByVal value As String)
                Me.campaignDestURLAddrField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property campaignStatus() As String
            Get
                Return Me.campaignStatusField
            End Get
            Set(ByVal value As String)
                Me.campaignStatusField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property campaignId() As String
            Get
                Return Me.campaignIdField
            End Get
            Set(ByVal value As String)
                Me.campaignIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property categoryName() As String
            Get
                Return Me.categoryNameField
            End Get
            Set(ByVal value As String)
                Me.categoryNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property counterPercent() As Single
            Get
                Return Me.counterPercentField
            End Get
            Set(ByVal value As Single)
                Me.counterPercentField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property counterPercentSpecified() As Boolean
            Get
                Return Me.counterPercentFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.counterPercentFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property customerName() As String
            Get
                Return Me.customerNameField
            End Get
            Set(ByVal value As String)
                Me.customerNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property dailyImpressionCount() As Single
            Get
                Return Me.dailyImpressionCountField
            End Get
            Set(ByVal value As Single)
                Me.dailyImpressionCountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dailyImpressionCountSpecified() As Boolean
            Get
                Return Me.dailyImpressionCountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dailyImpressionCountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property dailyPFPClickCount() As Single
            Get
                Return Me.dailyPFPClickCountField
            End Get
            Set(ByVal value As Single)
                Me.dailyPFPClickCountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dailyPFPClickCountSpecified() As Boolean
            Get
                Return Me.dailyPFPClickCountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dailyPFPClickCountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property dailyRawClickCount() As Single
            Get
                Return Me.dailyRawClickCountField
            End Get
            Set(ByVal value As Single)
                Me.dailyRawClickCountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dailyRawClickCountSpecified() As Boolean
            Get
                Return Me.dailyRawClickCountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dailyRawClickCountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set(ByVal value As String)
                Me.dateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property geographyName() As String
            Get
                Return Me.geographyNameField
            End Get
            Set(ByVal value As String)
                Me.geographyNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property geographyType() As String
            Get
                Return Me.geographyTypeField
            End Get
            Set(ByVal value As String)
                Me.geographyTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property maxBidAmount() As Single
            Get
                Return Me.maxBidAmountField
            End Get
            Set(ByVal value As Single)
                Me.maxBidAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property maxBidAmountSpecified() As Boolean
            Get
                Return Me.maxBidAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.maxBidAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property monthoDatePFPSpendAmount() As Single
            Get
                Return Me.monthoDatePFPSpendAmountField
            End Get
            Set(ByVal value As Single)
                Me.monthoDatePFPSpendAmountField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property monthoDatePFPSpendAmountSpecified() As Boolean
            Get
                Return Me.monthoDatePFPSpendAmountFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.monthoDatePFPSpendAmountFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property rankperBid() As RankingPerBid
            Get
                Return Me.rankperBidField
            End Get
            Set(ByVal value As RankingPerBid)
                Me.rankperBidField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property spendPercent() As Single
            Get
                Return Me.spendPercentField
            End Get
            Set(ByVal value As Single)
                Me.spendPercentField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property spendPercentSpecified() As Boolean
            Get
                Return Me.spendPercentFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.spendPercentFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://common.spapi.idearc.com")> _
    Partial Public Class Report

        Private createdDateField As String

        Private fromDateField As String

        Private reportIdField As String

        Private reportnameField As String

        Private reportTypeField As String

        Private statusField As String

        Private toDateField As String

        '''<remarks/>
        Public Property createdDate() As String
            Get
                Return Me.createdDateField
            End Get
            Set(ByVal value As String)
                Me.createdDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property fromDate() As String
            Get
                Return Me.fromDateField
            End Get
            Set(ByVal value As String)
                Me.fromDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property reportId() As String
            Get
                Return Me.reportIdField
            End Get
            Set(ByVal value As String)
                Me.reportIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property reportname() As String
            Get
                Return Me.reportnameField
            End Get
            Set(ByVal value As String)
                Me.reportnameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property reportType() As String
            Get
                Return Me.reportTypeField
            End Get
            Set(ByVal value As String)
                Me.reportTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set(ByVal value As String)
                Me.statusField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property toDate() As String
            Get
                Return Me.toDateField
            End Get
            Set(ByVal value As String)
                Me.toDateField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://common.spapi.idearc.com")> _
    Partial Public Class ReportList

        Private dateCreatedField As String

        Private reportField() As Report

        Private numberOfRowsField As String

        '''<remarks/>
        Public Property dateCreated() As String
            Get
                Return Me.dateCreatedField
            End Get
            Set(ByVal value As String)
                Me.dateCreatedField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False)> _
        Public Property report() As Report()
            Get
                Return Me.reportField
            End Get
            Set(ByVal value As Report())
                Me.reportField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property numberOfRows() As String
            Get
                Return Me.numberOfRowsField
            End Get
            Set(ByVal value As String)
                Me.numberOfRowsField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub scheduleReportCompletedEventHandler(ByVal sender As Object, ByVal e As scheduleReportCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class scheduleReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getReportURLCompletedEventHandler(ByVal sender As Object, ByVal e As getReportURLCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getReportURLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub deleteReportCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getDailySummaryReportCompletedEventHandler(ByVal sender As Object, ByVal e As getDailySummaryReportCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getDailySummaryReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As DailySummaryReport
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), DailySummaryReport)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getReportListCompletedEventHandler(ByVal sender As Object, ByVal e As getReportListCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getReportListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As ReportList
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), ReportList)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub getDailyReportCompletedEventHandler(ByVal sender As Object, ByVal e As getDailyReportCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class getDailyReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As DailyReport()
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), DailyReport())
            End Get
        End Property
    End Class
End Namespace